### ISSUE TITLE
Support sortByGroupSummaryInfo

### ISSUE THREAD

**Issue by erikmourits** [DevExpress/DevExtreme.AspNet.Data#124]
Hallo,

The dxDataGrid has an option: sortByGroupSummaryInfo. This allows sorting on grouped columns.
Not sure what else to type... if you need more info let me know.

Regards,
Erik

**Comment by AlekseyMartynov** [comment]
Thanks @erikmourits 
We see the issue.
It will be fixed on the dxDataGrid side: https://devexpress.com/issue=T526028
