### ISSUE TITLE
Please make DataSourceLoadResult public

### ISSUE THREAD

**Issue by twenzel** [DevExpress/DevExtreme.AspNet.Data#127]
Please make `DataSourceLoadResult` a public class so everyone can use it.

In our case it's required to access the result data in order to calculate some properties on the returned objects.

**Comment by AlekseyMartynov** [comment]
We've just published version `1.3.0-rc1`:

* https://www.nuget.org/packages/DevExtreme.AspNet.Data/1.3.0-rc1
* `npm i devextreme-aspnet-data@1.3.0-rc1`

2 new classes are available in the `DevExtreme.AspNet.Data.ResponseModel` namespace:

* `LoadResult`
* `Group`

**Comment by twenzel** [comment]
Thank you! Great Work.
