### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by twenzel** [DevExpress/DevExtreme.AspNet.Data#132]
If the LoadOptions have a single TotalSummary with a "count" aggregate, the DataSourceLoader will execute first a "SELECT Count(*).." statement to get the overall amount of items (required for pagination I guess) and then executes a statement WITHOUT a top/skip because it want's to calculate the summary in memory.

For this case (which very often exists) it could be much better if the summary is not calculated in memory and the already retrieved count value will be used.

**Comment by AlekseyMartynov** [comment]
Your suggestion is to skip [this block](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/1.3.0-rc1/net/DevExtreme.AspNet.Data/DataSourceLoaderImpl.cs#L111-L114) if the only summary item is total count which has already been calculated immediately before. Do I get the idea correctly?

**Comment by twenzel** [comment]
Yes, correct.

**Comment by AlekseyMartynov** [comment]
Included in 1.3.0-rc2
