### ISSUE TITLE
Provide error helper/logging

### ISSUE THREAD

**Issue by twenzel** [DevExpress/DevExtreme.AspNet.Data#136]
I've an error in my setup. The filter criteria does not fit to the queried entity.
Unfortunately the error ("'LeaseState' is not a member of type 'MyEntity'") won't bubble up to the developer. Instead the query will be created with an `.Where(false)` expression.

In some scenarios no one would even notice there's an error because the grid just shows no data.

Either let the exception (FilterExpressionCompiler.CompileCore) bubble up to the caller or provide any mechanism where the developer can check if any error occurred.

**Comment by AlekseyMartynov** [comment]
The `.Where(false)` fallback has been added intentionally for cases when end users enter unparseable / out-of-range values into filter row boxes (e.g. a negative number for an unsigned data type). 

Probably we need to catch only specific types such as `OverflowException` or `FormatException`. Would this work for your scenario?

**Comment by twenzel** [comment]
Yes, this would work.

**Comment by AlekseyMartynov** [comment]
Here's the changeset I suggest: #137 
try-catch is put lower and wraps only type conversion

**Comment by twenzel** [comment]
That's fine.

**Comment by AlekseyMartynov** [comment]
#137 merged
