### ISSUE TITLE
Weird query when using derived types

### ISSUE THREAD

**Issue by twenzel** [DevExpress/DevExtreme.AspNet.Data#138]
I've following class setting:

	public class Result
	{
		public int Value { get; set; }
		public string Name { get; set; }
	}	

	public class ResultExtended : Result
	{
		public int CustomerId { get; set; }
	}

When I use following call using the filter option

	var query = _provider.Get<Address>()
		.Where(a => a.ID > 10)
		.Select(a => new ResultExtended { CustomerId = a.County, Name = a.City });			

	var options = new TestLoadOptions
	{
		Skip = 0,
		Take = 10,
		Filter = new List<object> { "Name", "contains", "test" }
	};

	var result = DataSourceLoader.Load(query, options);

The resulting query looks like
`from Address a in Query(CHG.Demo.Objects.Address) where ([a].ID > 10) where new ResultExtended() {CustomerId = [a].County, Name = [a].City}.Name.ToLower().Contains("test") select new ResultExtended() {CustomerId = [a].County, Name = [a].City} => Take(10)`

But when I express the same query "directly"

	var query = _provider.Get<Address>()
		.Where(a => a.ID > 10)
		.Select(dto => new ResultExtended { CustomerId = dto.County, Name = dto.City })
		.Where(obj => obj.Name.ToLower().Contains("test"))
		.Take(10);

	var result = query.ToList();

the resulting query is correct
`from Address a in Query(CHG.Demo.Objects.Address) where ([a].ID > 10) where [a].City.ToLower().Contains("test") select new ResultExtended() {CustomerId = [a].County, Name = [a].City} => Take(10)`

I guess the expression builder if the `DataSourceLoader` creates a wrong expression when applying the filter.

_Update:_
By comparing the two expression trees I found out that the MemberExpression `obj.Name` are different. The MemberInfo of the first query says that the `ReflectedType` is `ResultExtended`, the value for the second query is `Result`.

So when I call it
`var result = DataSourceLoader.Load<Result>(query, options);`
the error is gone.

**Comment by AlekseyMartynov** [comment]
I assume that `query` is `IQueryable<Address>`.
Do you get the correct results from the `CreateQuery` call as shown below?

```c#
var query = _provider.Get<Address>()
    .Where(a => a.ID > 10)
    .Select(a => new ResultExtended { CustomerId = a.County, Name = a.City });

var predicateExpr = (Expression<Func<ResultExtended, bool>>)(r => r.Name.ToLower().Contains("test"));
var whereExpr = Expression.Call(typeof(Queryable), "Where", new[] { typeof(ResultExtended) }, query.Expression, Expression.Quote(predicateExpr));

query = query.Provider.CreateQuery<ResultExtended>(whereExpr);
query = query.Take(10);

var text = query.ToString();
```

**Comment by twenzel** [comment]
Yes, I do.

**Comment by AlekseyMartynov** [comment]
That's pretty strange. `DataSourceLoader` does approximately the same internally.
Also, it's unclear how the base type `Result` appears if the query is expressed in terms of `ResultExtended`.

I would like to isolate the case, but cannot get the results you describe with LINQ to Objects. Entity Framework produces reasonable SQL too.

My test case:

```c#
public class Issue138 {

    class Result {
        public int Value { get; set; }
        public string Name { get; set; }
    }

    class ResultExtended : Result {
        public int CustomerId { get; set; }
    }

    class Address {
        public int ID { get; set; }
        public int County { get; set; }
        public string City { get; set; }
    }

    class LoadOptions : DataSourceLoadOptionsBase { }

    [Fact]
    public void Scenario() {
        var source = new EnumerableQuery<Address>(Expression.Constant(null, typeof(IQueryable<Address>)));

        var query = source
            .Where(a => a.ID > 10)
            .Select(a => new ResultExtended { CustomerId = a.County, Name = a.City });

        var options = new LoadOptions {
            Skip = 0,
            Take = 10,
            Filter = new List<object> { "Name", "contains", "test" }
        };

        var result = DataSourceLoader.Load(query, options);

        // .Where(a => (a.ID > 10))
        // .Select(a => new ResultExtended() {CustomerId = a.County, Name = a.City})
        // .Where(obj => (IIF((obj == null), null, obj.Name) ?? "").ToLower().Contains("test"))
        // .Take(10)
    }

}
```

Any ideas appreciated.

**Comment by AlekseyMartynov** [comment]
I'm closing the issue for now. Once you have any additional info, please notify me by adding a comment.

**Comment by AlekseyMartynov** [comment]
FYI possibly a related issue: #154
