### ISSUE TITLE
README: missing code samples for MVC 5

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#143]
"Custom Model Binder" and "Controller Example" don't provide examples for MVC 5 controllers.

**Comment by RomanTsukanov** [comment]
There are no examples of MVC 5 controllers on GitHub. Let's add a sample MVC 5 project [here](https://github.com/DevExpress/DevExtreme.AspNet.Data/tree/master/net), let it mirror the existing Core MVC sample project. Once we have it, we can give the links in the README.

**Comment by AlekseyMartynov** [comment]
@RomanTsukanov 
please check https://github.com/DevExpress/devextreme-examples/pull/29

**Comment by RomanTsukanov** [comment]
@AlekseyMartynov cool, let's have it merged and get done with this issue

**Comment by AlekseyMartynov** [comment]
Merged
