### ISSUE TITLE
Migration from 1.2.6 to 1.30 results in errors

### ISSUE THREAD

**Issue by AceCoderYoda** [DevExpress/DevExtreme.AspNet.Data#155]
Migration to latest versions results in errors loading data.
  _result = DataSourceLoader.Load(source, loadOptions);
 IQueryable<T> _query = (IQueryable<T>)_result; <-- works in 1.2.6, fails in 1.3.0
changing above to 
 IQueryable<T> _query = (IQueryable<T>)((LoadResult)_result).data; <-- works partly in 1.3.0, fails on some occasions

**Comment by AceCoderYoda** [comment]
DataSourceLoader. Load returned an object in older versions which COULD BE cast as IQueryable
Now all results are LoadResult, which can't be converted to anything else but LoadResult.
Please provide an option to return IEnumerable<T>

**Comment by AlekseyMartynov** [comment]
> DataSourceLoader. Load returned an object in older versions which COULD BE cast as IQueryable

Exactly. The value was opaque, we didn't guarantee it to be of any exact type.

In 1.3.0, use `LoadResult.data`. However, its type is 'IEnumerable', it's not always a query, it can be a `List<Group>` for exampe.

**Comment by AceCoderYoda** [comment]
How is that better?
List<Group> or IEnumerable is still opaque.

**Comment by AlekseyMartynov** [comment]
To keep the dialogue in a constructive way, please let me know if you have any unresolved issues with the new response model classes. I'll be happy to assist you.

**Comment by AceCoderYoda** [comment]
The problem is as follows:
We define a result (` _result = DataSourceLoader.Load(source, loadOptions);`)
This variable (sometimes) results in an `IQuerable<T>`
Sometimes it will return `DataSourceLoadResult`
Whether this is right or wrong is another debate, the problem is that with the new version it will always return `LoadResult`.
This results in our datacalls failing. And because we call this generically (`MakeGenericMethod`) we cannot determine when we need `LoadResult `or `IQueryable`.

Now, this shouldn't have worked in the first place, but it did,  so now we are faced with this problem.
Below are the two functions involved

[CALLERFUNCTION]
`public JsonResult Load<T>(IQueryable<T> source, DataSourceLoadOptionsBase loadOptions, bool doNotApplyKeySorting = false)
        {
            object _result = null;

            if (RequestMode == RequestModeEnum.DataKeyOnly)
            {
                PropertyInfo _keyProp = GetKeyFromType(source.ElementType);
                if (_keyProp != null)
                {
                    var _dataProperty = _result.GetType().GetField("data");
                    IEnumerable<T> _query = (IEnumerable<T>)_dataProperty.GetValue(_result);
                    _dataProperty.SetValue(_result, _query.Select(_keyProp.Name));
                }
            }
            else if (RequestMode == RequestModeEnum.GetCurrent
                || RequestMode == RequestModeEnum.GetNext
                || RequestMode == RequestModeEnum.GetPrevious)
            {
                PropertyInfo _keyProp = GetKeyFromType(source.ElementType);
                if (_keyProp != null)
                {
                    if (_CallKeysMethod == null)
                    {
                        _CallKeysMethod = this.GetType().GetMethod("CallKeys");
                    }
                    var _mig = _CallKeysMethod.MakeGenericMethod(typeof(T), _keyProp.PropertyType);
                    _result = _mig.Invoke(this, new object[] { source, loadOptions, _keyProp.Name });
                }
            }
            else
            {
                if (!doNotApplyKeySorting)
                {
                    ExtendLoadOptionsSortWithKeySorting<T>(ref loadOptions);
                }
                _result = DataSourceLoader.Load(source, loadOptions);
            }
            var _json = Json(_result, JsonRequestBehavior.AllowGet);
            return _json;
        }`

[GENERICFUNTION]
` public object CallKeys<T, U>(IQueryable<T> source, DataSourceLoadOptionsBase loadOptions, string keyName) where U : new()
        {
            object _result = null;
            string _key = null;
            string _index = null;
            if (Request.Headers.AllKeys.Contains(HttpHeaders.PreviousNext, StringComparer.OrdinalIgnoreCase))
            {
                var _temp = Request.Headers.GetValues(HttpHeaders.PreviousNext)?.FirstOrDefault();
                var _temp2 = _temp.Split(',');
                _index = _temp2.Last();
                _key = _temp.Replace("," + _index, "");
            }
            TypeConverter _keyTypeConverter = TypeDescriptor.GetConverter(typeof(U));
            U _keyValue = (U)_keyTypeConverter.ConvertFromString(_key);
            TypeConverter _indexTypeConverter = TypeDescriptor.GetConverter(typeof(long?));
            long? _indexValue = (long?)_indexTypeConverter.ConvertFromString(_index);
            loadOptions.Take = 0;
            loadOptions.Skip = 0;


            ExtendLoadOptionsSortWithKeySorting<T>(ref loadOptions);
            _result = DataSourceLoader.Load(source, loadOptions);
            var _service = GetService<IItemSelectionHelperService>();
            IQueryable<T> _query = (IQueryable<T>)_result;
            if (RequestMode == RequestModeEnum.GetCurrent)
            {
                _result = _service.GetCurrentKey<T, U>(_query, _keyValue, keyName, _indexValue);
            }
            else if (RequestMode == RequestModeEnum.GetNext)
            {
                _result = _service.GetNextKey<T, U>(_query, _keyValue, keyName, _indexValue);
            }
            else if (RequestMode == RequestModeEnum.GetPrevious)
            {
                _result = _service.GetPreviousKey<T, U>(_query, _keyValue, keyName, _indexValue);
            }
            return _result;
        }`

**Comment by AlekseyMartynov** [comment]
Ok, from https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/155#issue-265694158 I see that you already found the solution:
```
IQueryable<T> _query = (IQueryable<T>)_result.data;
```

I'd like to understand the cases you mention here:

> works partly in 1.3.0, fails on some occasions

What is the runtime type of `_result.data` when it fails?

**Comment by AceCoderYoda** [comment]
First we cannot call `_result.data`
We have to call `_result = DataSourceLoader.Load(source, loadOptions).data;`

Type is` List<DbQuery>`
Most of this works, until we we check for Array clientside.
That returns [object Object] instead of [object Array].

**Comment by AceCoderYoda** [comment]
I think we solved by adding 
` if(sets.hasOwnProperty("data")){
            sets=sets["data"]
        }`

To our calling method

**Comment by AlekseyMartynov** [comment]
If the client-side script (dx.aspnet.data.js) is also updated to 1.3.0 this should not happen.
Can you confirm that servier-side and client-side versions match?

**Comment by AceCoderYoda** [comment]
Last remark. data is a public property in namespace ....Data. So I understand why it has no capital D. 
Consider renaming it Content. Public properties should be CamelCase

**Comment by AceCoderYoda** [comment]
It is updated using NuGet. So I would assume versions match up

**Comment by AlekseyMartynov** [comment]
The script is distributed via NPM and Bower, not via NuGet (a requirement of the .NET Core world).
Please, try updating the script. Docs: https://github.com/DevExpress/DevExtreme.AspNet.Data#client-side

Your remark regarding the use of camel case is perfectly valid. However, we use lower case for the sake of compatibility with various JSON serializers. Here is the [test case](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/4e611e51ce69d4acbed5d5e8283d0bc63502ee2e/net/DevExtreme.AspNet.Data.Tests/ResponseModelTests.cs#L32-L49).
