### ISSUE TITLE
Add public .NET API documentation

### ISSUE THREAD

**Issue by San4es** [DevExpress/DevExtreme.AspNet.Data#162]
- [x] setup DocFX
- [x] write the docs

**Comment by AlekseyMartynov** [comment]
@San4es instead of README I suggest to add a full DocFX documentation for .NET API.

**Comment by AlekseyMartynov** [comment]
DocFX project added in https://github.com/DevExpress/DevExtreme.AspNet.Data/commit/f0722125fb03014ce8a3dc9958662d3d93b08431

Check it by running the following commands in the repo dir:

```
dotnet build net/DevExtreme.AspNet.Data
net\docfx\build
net\docfx\serve
```

Resulting site: https://alekseymartynov.github.io/DevExtreme.AspNet.Data/net/api/DevExtreme.AspNet.Data.html

@RomanTsukanov the next step is to add XML doc comments to interesting public members.

**Comment by AlekseyMartynov** [comment]
@RomanTsukanov 
Published at https://devexpress.github.io/DevExtreme.AspNet.Data/net/api/DevExtreme.AspNet.Data.html
Please reference it from README.

**Comment by AlekseyMartynov** [comment]
Everything's done.
