### ISSUE TITLE
Support comparison operators for enums

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/DevExtreme.AspNet.Data#164]
The issue can be reproduced by modifying [this](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/894ff578af63cf9ffadda137de33bfef5d078ba2/net/DevExtreme.AspNet.Data.Tests/FilterExpressionCompilerTypeConversionTests.cs#L188-L199) test with the following code:
```C#
public void FilterByEnumField() {
            var structObj = new Structs();
            AssertEvaluation(structObj, "enum", "<", 3);
}
```

**Comment by AlekseyMartynov** [comment]
I'd like to know the use case.
Would you compare by value like [`Enum.CompareTo`](https://docs.microsoft.com/en-us/dotnet/api/system.enum.compareto?view=netframework-4.5) or by text?

**Comment by San4es** [comment]
@AlekseyMartynov 

See T584721.

**Comment by AlekseyMartynov** [comment]
Since there's no outstanding issue in T584721, I mark this as `enhancement`.
Easy to implement as soon as we understand use cases.

**Comment by AlekseyMartynov** [comment]
Closing, since we didn't receive any additional feedback.

**Comment by AlekseyMartynov** [comment]
@shcheglovvladimir has reported this issue today.
The same case as in #339 (filter issued by Data Grid to find focused row index).
