### ISSUE TITLE
Make jQuery dependency optional

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/DevExtreme.AspNet.Data#169]
The DevExpress.data.AspNet.createStore method returns a data storage that does not operate without the jQuery library.

**Comment by AlekseyMartynov** [comment]
A blog post explaining the motivation behind this issue:
[DevExtreme with and without jQuery (v17.2)](https://community.devexpress.com/blogs/donw/archive/2017/11/09/devextreme-with-and-without-jquery-v17-2.aspx)

**Comment by AlekseyMartynov** [comment]
@NickMitrokhin 
I made a decent progress on this task.
Changes: https://github.com/DevExpress/DevExtreme.AspNet.Data/compare/master...AlekseyMartynov:jq
Some tests fail https://ci.appveyor.com/project/AlekseyMartynov/devextreme-aspnet-data/build/190
(seems we need to make some improvements in our $.ajax surrogate)
/cc @ovchinnikov

**Comment by AlekseyMartynov** [comment]
We need to support explicit `cache=false` [here](https://github.com/DevExpress/DevExtreme/blob/50028759377fcd7f4b1386b29a0e0abe567f3a21/js/core/utils/ajax.js#L240)

**Comment by AlekseyMartynov** [comment]
@RomanTsukanov please check [this message](https://github.com/AlekseyMartynov/DevExtreme.AspNet.Data/blob/8c30ac296d4975ad02fb9dbcdc39e3e9bb761776/build/make-nojquery.js#L12)

**Comment by RomanTsukanov** [comment]
@AlekseyMartynov the message is alright

**Comment by AlekseyMartynov** [comment]
#178 merged
