### ISSUE TITLE
Add a doc/wiki describing how to use CI builds in projects

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#173]
See https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/85#issuecomment-277993703

**Comment by AlekseyMartynov** [comment]
Navigate to [AppVeyor master branch build artifacts](https://ci.appveyor.com/project/dxrobot/devextreme-aspnet-data/branch/master/artifacts).

Download the following files to a temporary location (e.g. C:\temp):
- devextreme-aspnet-data-99.0.0-ci-NNN.tgz
- DevExtreme.AspNet.Data.99.0.0-ci-NNN.nupkg

### Client-side script

Extract the `.tgz` file. On Windows, you can use [7zip](http://www.7-zip.org/download.html) for that:

```bash
7zip x devextreme-aspnet-data-99.0.0-ci-NNN.tgz
7zip x devextreme-aspnet-data-99.0.0-ci-NNN.tar
```

Find the extracted JavaScript file in the package/js directory. Copy it to your project.

Alternatively, for Node projects, install the package directly:

```bash
npm i /temp/path/devextreme-aspnet-data-99.0.0-ci-NNN.tgz
```

Alternatively, download [directly from GitHub master branch](https://raw.githubusercontent.com/DevExpress/DevExtreme.AspNet.Data/master/js/dx.aspnet.data.js).

### NuGet package

Install the downloaded NuGet package (`.nupkg` file) using one of the approaches described in [How to install a Nuget Package .nupkg file locally](https://stackoverflow.com/a/35753968).

### Assembly binding redirect

For .NET framework projects, add a binding redirect to web.config or app.config file:

```xml
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <!-- add this -->
      <dependentAssembly>
        <assemblyIdentity name="DevExtreme.AspNet.Data" publicKeyToken="982f5dab1439d0f7"/>
        <bindingRedirect oldVersion="0.0.0.0-99.0.0.0" newVersion="99.0.0.0"/>
      </dependentAssembly>
```

**Comment by AlekseyMartynov** [comment]
Hi @RomanTsukanov 

I plan to add text from https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/173#issuecomment-357634531 to somewhere in the repo (I think of docs/fancy-name.md).

May you please review it, make any necessary edits, and also suggest a good filename?

**Comment by RomanTsukanov** [comment]
Master branch build artifacts are stored [here](https://ci.appveyor.com/project/dxrobot/devextreme-aspnet-data/branch/master/artifacts). Download the `devextreme-aspnet-data-99.0.0-ci-NNN.tgz` file and use the instruction for the client-side script, or get `DevExtreme.AspNet.Data.99.0.0-ci-NNN.nupkg` and follow the one for the NuGet package.

### Client-Side Script

Unpack the `.tgz` archive to a temporary location. On Windows, you can use [7zip](http://www.7-zip.org/download.html) for that:

```bash
7zip x devextreme-aspnet-data-99.0.0-ci-NNN.tgz
7zip x devextreme-aspnet-data-99.0.0-ci-NNN.tar
```

Navigate to the package/js folder in this location and copy the extracted JavaScript file to your project.

For Node projects, you can install the archive as a package:

```bash
npm i /temp/path/devextreme-aspnet-data-99.0.0-ci-NNN.tgz
```

Alternatively, you get the JavaScript file directly [from the master branch](https://raw.githubusercontent.com/DevExpress/DevExtreme.AspNet.Data/master/js/dx.aspnet.data.js) on GitHub.

### NuGet Package

Install the `.nupkg` package using the instructions from [How to install a Nuget Package .nupkg file locally](https://stackoverflow.com/a/35753968).

### Add an Assembly Binding Redirect

For .NET framework projects, add a binding redirect to the `web.config` or `app.config` file:

```xml
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <!-- add this -->
      <dependentAssembly>
        <assemblyIdentity name="DevExtreme.AspNet.Data" publicKeyToken="982f5dab1439d0f7"/>
        <bindingRedirect oldVersion="0.0.0.0-99.0.0.0" newVersion="99.0.0.0"/>
      </dependentAssembly>
```

**Comment by RomanTsukanov** [comment]
As for the filename, I suggest `using-ci-builds-in-development.md`

**Comment by San4es** [comment]
Why not just `using-ci-builds.md`? ~Wher else CI builds can be used?~ :)

**Comment by AlekseyMartynov** [comment]
@RomanTsukanov 
Thanks. However. I was hoping for a PR 🤔

**Comment by RomanTsukanov** [comment]
@AlekseyMartynov 
You got it

@San4es I don't know, for distributing :) I kept "in development" for now. Aleksey, how do you think?

**Comment by AlekseyMartynov** [comment]
I commented in https://github.com/DevExpress/DevExtreme.AspNet.Data/pull/176#issuecomment-358235786

**Comment by RomanTsukanov** [comment]
@AlekseyMartynov renamed it as suggested by @San4es
