### ISSUE TITLE
master fails on insert/update/remove with "Unexpected server response"

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#192]
Caused by 

https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/03fa77aa8eea6ad7a7106094fc41ab448fa7bbcc/js/dx.aspnet.data.js#L51

WIP: https://github.com/AlekseyMartynov/DevExtreme.AspNet.Data/tree/cud-tests
Blocked on https://github.com/DevExpress/DevExtreme/pull/2879

FYI @San4es

**Comment by AlekseyMartynov** [comment]
@NickMitrokhin 
Please schedule a public fix build (17.2)

**Comment by San4es** [comment]
@AlekseyMartynov 

DevExtreme@17.2.6-pre-18038 with the https://github.com/DevExpress/DevExtreme/pull/2879 fix is published.
