### ISSUE TITLE
Remove MVC dependency

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#2]
Why?

* To have a single build/package suitable for MVC 5, MVC 6 and any other platform
* To have stable dependencies, therefore be able to publish a non-preview package

Drawbacks

* `DataSourceLoadOptions` and `DataSourceLoadOptionsBinder` must be defined externally (like [here](https://github.com/AlekseyMartynov/DevExtreme.AspNet.Data/blob/ecc3d9811d69780678506f8773ce0fd3c0cd6f13/net/Sample/DataSourceLoadOptions.cs)).

Work started in https://github.com/AlekseyMartynov/DevExtreme.AspNet.Data/tree/no-mvc

@IlyaKhD when you have a minute, please review and share your thoughts

**Comment by IlyaKhD** [comment]
I agree this is a good idea to remove the dependency from a specific MVC version.

On the other hand these version specific things are to be implemented in the users project (i.e. `IModelBinder` impl) though it's a common code that is likely to be the same across all projects. May be it would be useful to have extra NuGet packages for that purposes (these are version specific).

How do you think?

**Comment by AlekseyMartynov** [comment]
I plan to start with including `DataSourceLoadOptionsBinder` implementation into our TagHepers package. Later (when ASP.NET Core has a stable release) , we'll be able to seamlessly introduce extra NuGets as you suggest.

**Comment by IlyaKhD** [comment]
Yep, the TagHelpers package is a good option for now, and no temporary packages are required.
