### ISSUE TITLE
HttpInterceptor does not work. How do I change the header a request?

### ISSUE THREAD

**Issue by Andrey-Ostapenko** [DevExpress/DevExtreme.AspNet.Data#201]
I need to add a token, but HttpInterceptor does not work for DevExtreme.AspNet.Data

@Injectable()
export class MyInterceptor implements HttpInterceptor {
 ...
const bearer = `Bearer ${token}`;
req = req.clone({headers: req.headers.set('Authorization', bearer)});
...
}

Use
Angular 5+ 
and
import * as AspNetData from 'devextreme-aspnet-data-nojquery';

**Comment by bahodirk** [comment]
Hello, I have the same issue. Have you managed to solve this. Thank you

**Comment by pilouk** [comment]
what did you do ? same problem here
