### ISSUE TITLE
LoadOptions are not assigned

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme.AspNet.Data#209]
I am using Web API example on the backend and Devextreme OData store on the client side. However no matter what options I use on the client side (GET request), loadOptions parameter on the backend is never populated with anything. Any idea what might be the problem?

**Comment by AlekseyMartynov** [comment]
On the client side, `ODataStore` won't work.
Client-server communication is carried out using a custom protocol, not OData.

Use `DevExpress.data.AspNet.createStore` instead:

https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/388684d5dfa994685d0da8bb540adaa87a6c36c6/net/Sample/Views/Home/Index.cshtml#L9-L20

The API is described in [README](https://github.com/DevExpress/DevExtreme.AspNet.Data#client-side-1).

**Comment by hakimio** [comment]
Thank you. Can I see somewhere protocol specification?

**Comment by AlekseyMartynov** [comment]
It's not documented. However the parser code should describe it quite well:
[DataSourceLoadOptionsParser.cs](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/1.3.0/net/DevExtreme.AspNet.Data/Helpers/DataSourceLoadOptionsParser.cs)
