### ISSUE TITLE
Make the result of FilterExpressionCompiler public

### ISSUE THREAD

**Issue by Franki1986** [DevExpress/DevExtreme.AspNet.Data#211]
It would be nice if there is a possibility to access the generated filter Expression without executing the filter. So you could work with the expression without accessing the database layer.

**Comment by AlekseyMartynov** [comment]
Do I understand correctly that you suggest to publish the [`FilterExpressionCompiler<T>`](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/1.3.0/net/DevExtreme.AspNet.Data/FilterExpressionCompiler.cs) class?
Which use cases would this be useful for?

**Comment by Franki1986** [comment]
I would like to use the result expression from client side and combine them with more complex queries on the server.

**Comment by AlekseyMartynov** [comment]
For `AND`-style combining you can write:

```c# 
var preFiltered = source.Where(serverLambda);

return DataSourceLoader.Load(preFiltered, loadOptions);
```

If a more complicated customization is needed, then do you have an example of how the resulting code might look like? Is it a sort of a hook/callback to adjust the filtering phase, or something else?

**Comment by Franki1986** [comment]
I have to make database acceses over wcf to many clients. Most of them don't have high speed connections, so I have to filter as much as I can on th database that is on their side. So if I have your filter control extracting the linq expression, i could combine it with other controls values in the expression and send it to the server. There I access the database with linq2db. Based on the database version of my clients, I then habe to create the query on the server side.

**Comment by AlekseyMartynov** [comment]
I still need a better understanding. Do you use the `DataSourceLoader` class? Do you feed data to DevExtreme widgets? Or do you only need to dynamically build expression trees like `System.Linq.Dynamic` does? What is the 'filter control' you refer to?

**Comment by Franki1986** [comment]
It is a complex scenario. Our company is moving from Devexpress ASP.NET Webforms to Devextreme widgets. So I have often grids where the column filter is used, and an additional custom filter control is used.  So one case is that I have a grid with payment transactions. Now I have made a custom control that shows all day accounts of the running year. Based on the selection of this control the result is a id list. So the id list and the filter that is applied by the grid are combined to a join, that is made on another machine that accesses the database. But based on which database version is on the clients machine, the join is different. So at the end I would like to send a string wich contains the complete linq expression (e.g System.linq.Dynamic.Core) over the wcf service, or better serialize the linq expression with [linq expression serializer](https://github.com/esskar/Serialize.Linq). So I would like to use your DevExtreme.AspNet.Data component in all my grid datasources because I like the way it works and in some cases combine it with my custom filter controls.

**Comment by AlekseyMartynov** [comment]
Ok, now I understand that you need to combine grid's internal filter with a list of IDs provided by an external control, and the way they are combined may vary.

It seems that this can be done by editing the `DataSourceLoadOptions.Filter` property before calling `DataSourceLoader.Load`. You'll operate in terms of DevExtreme filter expressions which are nested lists.

E.g. if the id list is passed via `loadParams`:

```c#
[HttpGet]
public HttpResponseMessage Get(DataSourceLoadOptions loadOptions, int[] ids) {
    loadOptions.Filter = /* any logic required to combine with `ids` */;

    return Request.CreateResponse(DataSourceLoader.Load(_source, loadOptions));
}
```
If it's not sufficient, then we can consider adding a callback in which a developer can rewrite compiled filter expressions. Something like:

```c#
loadOptions.CustomizeFilter = expr => {
    return /* new expression */;
};
```
Do I miss anything?

**Comment by Franki1986** [comment]
This sounds like a plan! Anyhow, the suggestion with CustomizeFilter.. sounds interesting. I am a fan of customizable components!

**Comment by Franki1986** [comment]
I am using the client side api, but don't know where to put the additional parameter?
There is only a load url, isn't there something like a before load where I can pass additional parameters? 

    `store = AspNetData.createStore`

**Comment by AlekseyMartynov** [comment]
Use either `loadParams`: 

```
const myLoadParams = { };

const store = AspNetData.createStore({
    loadParams: myLoadParams
})

myLoadParams.p1 = 123;
store.load()
```

or `onBeforeSend`:

```
AspNetData.createStore({
    onBeforeSend: function(operation, ajax) {
        if(operation === "load") {
            ajax.data["my"] = 123;
        }
    }
})
```

[API Reference](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/docs/client-side-with-jquery.md#api-reference)

**Comment by AlekseyMartynov** [comment]
Hello @Franki1986 
Is the original request, to make the result of `FilterExpressionCompiler` public, still relevant?
As I understand, the issues have been resolved without rewriting LINQ expressions.

**Comment by Franki1986** [comment]
Hello Aleksey! Sorry for late response, I have become the second time father in the meanwhile :-)

The workaround works fine for me!
