### ISSUE TITLE
DataSourceLoader only query against the result set from entity framework, does it mean it's doing 2nd query?

### ISSUE THREAD

**Issue by acidpassion** [DevExpress/DevExtreme.AspNet.Data#222]
1) Query DB without filter
2) Query the result set from DB?

What's the best approach to improve the performance?

**Comment by AlekseyMartynov** [comment]
Depending on load options, `DataSourceLoader` can build one or multiple queries as well as perform some in-memory post-processing.

Using SQL Server Profiler, you can trace the actual SQL.

In general, we try to postpone query execution as long as possible.
For example, the code below doesn't necessary mean that the first `Where` is executed independently.
Usually, load options are appended to the existing quiery and later executed as a whole.

```c#
var subset = db.Set1.Where(...);
DataSourceLoader.Load(subset, ...);
```
