### ISSUE TITLE
Customer Header Overwrite the dxDataGrid parameters to api

### ISSUE THREAD

**Issue by acidpassion** [DevExpress/DevExtreme.AspNet.Data#223]
this.dataSource = AspNetData.createStore({
        key: "id",
        loadUrl: this.url + "/GetTrades",
        insertUrl: this.url + "/InsertTrade",
        updateUrl: this.url + "/UpdateTrade",
        deleteUrl: this.url + "/DeleteTrade",
        onBeforeSend: function(method, ajaxOptions) {
          ajaxOptions.xhrFields = { withCredentials: true, test:true};
          ajaxOptions.headers = {         
            'Authorization': "bearer " + Authorization,
            'Content-Type': 'application/json',
            'ptsEntity' : authService.getPtsEntity()
          };
      }
    });

I set this custom header, but on data grid update, there is no more form data sent to api.

**Comment by AlekseyMartynov** [comment]
Instead of overwriting headers, add individual entries:

```js
ajaxOptions.headers['Authorization'] = "bearer " + Authorization;
```

Don't override `Content-Type`.
