### ISSUE TITLE
add operator "IN" to Filter

### ISSUE THREAD

**Issue by sergsuhanov** [DevExpress/DevExtreme.AspNet.Data#226]
```
[HttpGet]
public HttpResponseMessage Get(DataSourceLoadOptions loadOptions, int[] ids) {
    loadOptions.Filter = /* any logic required to combine with `ids` */;

    return Request.CreateResponse(DataSourceLoader.Load(_source, loadOptions));
}
```

To make it work, you need to use the 'OR' operator:
```
string key = ...;
bool _f = false;
foreach (var id in ids) {
    if (_f)
        arr.Add("OR");
    else 
        _f = true;
    
    var filter = new Newtonsoft.Json.Linq.JArray(key, "=", id);
    loadOptions.Filter.Add(filter);
}
```
and if many keys this becomes a problem.

It would be better to do the following:
```
[HttpGet]
public HttpResponseMessage Get(DataSourceLoadOptions loadOptions, int[] ids) {
    loadOptions.Filter = new Newtonsoft.Json.Linq.JArray(key, "IN", ids);

    return Request.CreateResponse(DataSourceLoader.Load(_source, loadOptions));
}

```

**Comment by AlekseyMartynov** [comment]
In this particular case, there's a better, strongly typed way:

```c#
var prefiltered = _nwind.Orders.Where(o => ids.Contains(o.EmployeeID));
return DataSourceLoader.Load(prefiltered, loadOptions);
```

which gives:

```sql
SELECT . . .
FROM [Orders] AS [o]
WHERE [o].[EmployeeID] IN (1, 2, 3)
ORDER BY [o].[OrderID]
```

As for the original subject, we have an [old Support Center thread](https://devexpress.com/issue=Q98554#answer-552990d0-dc23-4c5f-b6f4-895b04a0f50b) in which our devs measured that there's no difference between `IN` and multi `OR`:

>  We've just changed our code for the IN query, evaluated the performance and ...haven't noticed any difference . . .

What is the exact problem you ran into?

**Comment by sergsuhanov** [comment]
When using many "Or" when using the POST Get query, you can exceed the maximum length.
I solved my question, I extract / delete "IN" filter from loadOptions and apply it to the data source manually. Thank you.
