### ISSUE TITLE
Dynamic Binding Nested ExpandoObject

### ISSUE THREAD

**Issue by aldycool** [DevExpress/DevExtreme.AspNet.Data#227]
Hi,

The dynamic binding support (with ExpandoObject) works well if using primitive types only. But when using an ExpandoObject as one of its dictionary value, hoping that I can do Filter with key "Company.Name" equals to something ("Company" is the key from the root ExpandoObject, while "Name" is the key from the nested ExpandoObject), an error raised like "ExpandoObject doesn't have key Company.Name". Is there's a way to achieve this? Thanks

**Comment by AlekseyMartynov** [comment]
It's a bug!

Here:
https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/f7344deea3cd098e74d5e8cecfa73bec70dd80a6/net/DevExtreme.AspNet.Data/ExpressionCompiler.cs#L39

`clientExprItem` must be used instead of `clientExpr`.

We'll fix it and release an update shortly.
Thank you.

**Comment by AlekseyMartynov** [comment]
Fixed in [1.4.2](https://github.com/DevExpress/DevExtreme.AspNet.Data/releases/tag/1.4.2)
