### ISSUE TITLE
grouping with remote grouping for join not working

### ISSUE THREAD

**Issue by Franki1986** [DevExpress/DevExtreme.AspNet.Data#229]
Hello,

I am using [LinqToDb](https://github.com/linq2db/linq2db) as database framework (if you use it you don't want to use EF again :-) ).
Everything works fine for a normal query with a dx-grid. Buit if I try to create a left join query and access the header filter, the created query will fail.

This is my join:

```
var r = from k in this.GetTable<Person>() join ks in this.GetTable<Student>() on new Tuple<int, string>(k.Id, k.Number.ToString()) equals
               new Tuple<int, string>(ks.Id, ks.Number) into joinedTable
               from g in joinedTable.DefaultIfEmpty()
                    select new Person(k) {
            IsBlocked = (k.StatusBitmask & 0x80) != 0, IsBlockedStudent = (g.StatusBitmask & 0x80) != 0 };
```

The reault in the grid works perfect:

```
[HttpGet]
      [Route("with-filter")]
      public HttpResponseMessage GetFiltered( [FromUri]DataSourceLoadOptions loadOptions)
      {
         LoadResult result = null;
         try
         {
            loadOptions.RemoteSelect = true;
            loadOptions.RequireTotalCount = true;
            using(var db = DbContext())
            {
               // Get joined result will retrieve the joined query.
               result = DataSourceLoader.Load(db.GetJoinedResult(), loadOptions);
            }            
         }
         catch (Exception ex)
         {
            return new HttpResponseMessage(HttpStatusCode.InternalServerError);
         }
         
         return Request.CreateResponse(result);
      }
```

The resulting sql is the following:

```
-- Firebird
SELECT
	Count(*) as c1,
	0 as c2
FROM
	PERSON k1
		LEFT JOIN STUDENT joinedTable ON k1.ID = joinedTable.ID AND Cast(k1.NUMBER as VarChar(11) CHARACTER SET UNICODE_FSS) = joinedTable.NUMBER
ORDER BY
	0
```

This does not work, because the order by is not valid. And I am not sure if this is the desired query?

**Comment by AlekseyMartynov** [comment]
`db.GetJoinedResult().Count()` - does this work?

**Comment by Franki1986** [comment]
Yes this works like expected. The resulting sql is:

```
-- Firebird
SELECT
	Count(*) as cnt
FROM
	PERSON k1
		LEFT JOIN STUDENT joinedTable ON k1.ID = joinedTable.ID AND Cast(k1.NUMBER as VarChar(11) CHARACTER SET UNICODE_FSS) = joinedTable.NUMBER
```

**Comment by AlekseyMartynov** [comment]
Ok. What are inner properties of `loadOptions`?
I'd like to recreate the problematic expression.

**Comment by Franki1986** [comment]
So the only thing I do is using dx-grid with all opzions on remote filter sorting grouping and so on. So I have skip and take for the grid. But for the header filter the only thing that is passed is a group info. So when I click on the header filter there is only a group info nothing else, no sort or skip or take or filter. The group is sorted automatically like I understand.

**Comment by AlekseyMartynov** [comment]
Grouping is used to [load distinct data items](https://stackoverflow.com/q/164319) for the header filter popup.

AJAX request:

```
?group=[{"selector":"A","isExpanded":false}]
```

Expression:

```c#
source
    .GroupBy(obj => new { 
        I0 = obj.A
    })
    .OrderBy(g => g.Key.I0)
    .Select(g => new {
        I0 = g.Count(), 
        I1 = g.Key.I0
    })
```

Try a similar query on `db.GetJoinedResult()`.
If it doesn't fail then I'll need a sample project to debug.

**Comment by Franki1986** [comment]
This also fails:

```
db.GetJoinedResult().GroupBy(x => new {I0 = x.Number})
    .OrderBy(g => g.Key.I0)
        .Select(g => new {I0 = g.Count(), I1 = g.Key.I0}).ToList();
```

resulting sql:

```
SELECT
	Count(*) as c1,
	0 as c2
FROM
	PERSON k1
		LEFT JOIN STUDENT joinedTable ON k1.ID = joinedTable.ID AND Cast(k1.NUMBER as VarChar(11) CHARACTER SET UNICODE_FSS) = joinedTable.NUMBER
ORDER BY
	0
```

**Comment by Franki1986** [comment]
Nit 100% sure, but this could be a linq2db bug.

**Comment by Franki1986** [comment]
Checked this with the guys at LinqToDb. It is the cause of using the copy constructor in the GetJoinedResult(), so the grouping had no data to group.
Without using a copy constructor, but setting the properties directly in the select statement, this works.
Thanks for your work!
