### ISSUE TITLE
Error in project.assets.json file when trying to compile

### ISSUE THREAD

**Issue by abukres** [DevExpress/DevExtreme.AspNet.Data#230]
When trying to compile the solution I get the error below. The Target Framework in Visual Studio is blank and disabled.  It seems there's something missing on my machine but I am not sure what it is. An old version of some SDK?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Assets file 'C:\inetpub\wwwroot\DevExtreme.AspNet.Data-master\net\DevExtreme.AspNet.Data\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v1.0'. Ensure that restore has run and that you have included 'netstandard1.0' in the TargetFrameworks for your project.	DevExtreme.AspNet.Data	C:\Program Files\dotnet\sdk\2.1.102\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167

**Comment by AlekseyMartynov** [comment]
Try to manually delete the `bin` and `obj` directories in every failing project. Or make a fresh clone of the repo.
