### ISSUE TITLE
DataSourceLoadOptionsBase: use properties instead of fields for public members

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#231]
Originally requested in https://devexpress.com/issue=T624663
More insights: https://stackoverflow.com/q/2374416

**Comment by statler** [comment]
Any progress on this?

**Comment by bbakermmc** [comment]
Why not just include the bind able class and conversion method as an option in V1 for now.  Im running in to the same same issue where I have a dynamic webapi but it cant see the values, so I ether need to make this bind able class for it to get the values it can set or pass in a string and parse the json to object.

**Comment by AlekseyMartynov** [comment]
@bbakermmc 
If I understand correctly, you are talking about ASP.NET Boilerplate dynamic controllers. According to their [docs](https://aspnetboilerplate.com/Pages/Documents/Dynamic-Web-API#about-parameter-binding), model binders should work (see our [docs](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/docs/server-side-configuration.md#custom-model-binder) and [example](https://github.com/DevExpress/devextreme-examples/blob/18_1/datagrid-webapi/datagrid-webapi/DataSourceLoadOptions.cs)). Replacing fields with properties won't make binding automatic.

When model binders don't work, you can use `DataSourceLoadOptionsParser` directly from an action method:

```c#
var loadOptions = new MyLoadOptions(); // a subclass of DataSourceLoadOptions
var query = Request.GetQueryNameValuePairs();
DataSourceLoadOptionsParser.Parse(loadOptions, name => query.FirstOrDefault(i => i.Key == name).Value);
```

or

```c#
var loadOptions = new MyLoadOptions(); // a subclass of DataSourceLoadOptions
DataSourceLoadOptionsParser.Parse(loadOptions, name => Request.QueryString[name]);
```

**Comment by bbakermmc** [comment]
@AlekseyMartynov correct.  If I make a subclass with getters/setters and then return back a DataSourceLoadOption it works...  My original issue is the dynamic controller created an empty parameter list for the the DataSourceLoadOption class.  

Not sure if youre familiar with the framework but the dynamic api converts app services over to webapi and js actions.

EX:  You see how the 2nd method has no input variables.  (If I make a subclass with getters/setters etc, it generates the parameters)

 ```c#
[DontWrapResult]
        public virtual object GetAllDevExtremeByJsonOptions(string input, bool withIncludes = true)
        {
            CheckGetPermission();
            
            DataSourceLoadOptions options;
            if (!string.IsNullOrEmpty(input))
            {
                options = JsonConvert.DeserializeObject<DataSourceLoadOptions>(input, new JsonSerializerSettings {ContractResolver = new DefaultContractResolver()});
            }
            else
            {
                throw new UserFriendlyException("LoadOptions is Null!", "The load options should not be empty for a DevExtreme end point!");
            }

            return GetAllDevExtreme(options, withIncludes);
        }

        [DontWrapResult]
        public virtual object GetAllDevExtreme(DataSourceLoadOptions input, bool withIncludes = true)
        {
            CheckGetPermission();

            return DataSourceLoader.Load(GetAllQueryable(withIncludes), input).ToJsonString(false, true);
        }
```

```JS
// action 'getAllDevExtremeByJsonOptions'
    abp.services.app.bRC.getAllDevExtremeByJsonOptions = function(input, withIncludes, ajaxParams) {
      return abp.ajax($.extend(true, {
        url: abp.appPath + 'api/services/app/BRC/GetAllDevExtremeByJsonOptions' + abp.utils.buildQueryString([{ name: 'input', value: input }, { name: 'withIncludes', value: withIncludes }]) + '',
        type: 'GET'
      }, ajaxParams));;
    };

    // action 'getAllDevExtreme'
    abp.services.app.bRC.getAllDevExtreme = function(input, withIncludes, ajaxParams) {
      return abp.ajax($.extend(true, {
        url: abp.appPath + 'api/services/app/BRC/GetAllDevExtreme' + abp.utils.buildQueryString([{ name: 'withIncludes', value: withIncludes }]) + '',
        type: 'GET'
      }, ajaxParams));;
    };
```

This is what I was trying to do:  (which now works if I just pass the JSON over and convert in the method above, Is there a better way that you know of?)
```js
var gridData = new DevExpress.data.DataSource({
            load: function(loadOptions) {
                abp.log.debug("Initial Load Options:");
                abp.log.debug(loadOptions);
                abp.log.debug(stringToPascalJSON(loadOptions));
                var deferred = $.Deferred();
                abp.services.app.bRC.getAllDevExtremeByJsonOptions(JSON.stringify(stringToPascalJSON(loadOptions)))
                    .done(function(result) {
                        abp.log.debug("Response");
                        abp.log.debug(result);
                        deferred.resolve({ data: result.data, totalCount: result.totalCount });
                    });
                return deferred.promise();
            },
            byKey: function(key) {
                abp.log.debug("ByKey: " + key);
                return { id: key };
            }
        });
```

**Comment by AlekseyMartynov** [comment]
@bbakermmc 
To not clutter up this ticket, I'm moving ASP.NET Boilerplate discussion to a dedicated ticket #268

**Comment by AlekseyMartynov** [comment]
@bbakermmc 
To not clutter up this ticket, I'm moving ASP.NET Boilerplate discussion to #268
