### ISSUE TITLE
show custom error message from the data base

### ISSUE THREAD

**Issue by joankent** [DevExpress/DevExtreme.AspNet.Data#270]
hi, how can show the error message directly from the data base? thanks.

**Comment by joankent** [comment]
thanks, can you see my code?, I need show message on updating process

jQuery Code:
var url = "<?php echo $this->createUrl('mayofiletypes', array('id'=>$id))?>";		
		var dbmc = new DevExpress.data.AspNet.createStore({
			key: "MayoFileTypeID",
			loadUrl: url,
			loadParams: { "load": 1 },
			insertUrl: url,
			updateUrl: url,
			deleteUrl: url,
			loadMethod: "POST",
			updateMethod: "POST",
			insertMethod: "POST",
			deleteMethod: "POST"
		});
		
		$("#myTableMayoFiles").dxDataGrid({
			dataSource: { 
				store: dbmc
			},
			columnHidingEnabled: false,
			allowColumnResizing: true,
			columnResizingMode: "nextColumn",
			columnMinWidth: 50,
			columnAutoWidth: true,		
			showColumnLines: true,
			showRowLines: true,
			rowAlternationEnabled: true,
			showBorders: true,		
			height: 280, 
			width: "100%",
			selection: {
				mode: "multiple", 
				allowSelectAll: false
			},
			stateStoring: {
				enabled: false,
				type: "localStorage",
				storageKey: "storage"
			},
			"export": {
				enabled: false,
				fileName: "Uploadfiles",
				allowExportSelectedData: false
			},		
			paging: {
				enabled: true,
				pageSize: 50
			},
			pager: {
				showPageSizeSelector: true,
				allowedPageSizes: [50, 100, 500, 1000],
				showInfo: true
			},
			searchPanel: {
				visible: false
			},
			editing: {
				mode: "batch",
				allowAdding: true,
				allowUpdating: true,
				allowDeleting: true,
				method: "POST",
			},
			columns: [ 
				{  caption: "ID", dataField: "MayoFileTypeID", visible: false },
				{  caption: "Mayorista", dataField: "MayoID", visible: false, width: 150 },
				{  caption: "FileType", dataField: "FileTypeID", lookup: { dataSource: fileTypes, valueExpr: "id", displayExpr: "name" }, width: 100 },
				{  caption: "Company", dataField: "CiaID", lookup: { dataSource: cias, valueExpr: "id", displayExpr: "name" }, width: 100 },
				{  caption: "Mask", dataField: "Mask", validationRules: [{ type: "required" }], width: 150 }
			],
			remoteOperations: {
				filtering: true,
				grouping: true,
				groupPaging: true,
				paging: true,
				sorting: true,
				summary: true  
			},		
			onCellPrepared: function(e) {
			},
			onContentReady: function (e){
			},		
			onRowUpdated: function(e){
			},
			onRowInserted: function(e){
			},
			onRowRemoved: function(e){
			},
		});

php Code:


try{
        $result = Yii::app()->db->createCommand("INSERT INTO pbis_data.FFS_Mayo_Cia (............) VALUES (..............)")->query();
} catch(Exception $e){
	echo $e->getMessage();
}


then my problem is I need know how can I show this message in datagrid.

**Comment by AlekseyMartynov** [comment]
This should do the trick:

```php
header("HTTP/1.0 500 Server Error");
header("Content-Type: text/plain");
die($e->getMessage()); 
```

For details, see [`getErrorMessageFromXhr`](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/2a8c46ecc380efd6850d309b7dd2f7e953c18bef/js/dx.aspnet.data.js#L316).

**Comment by joankent** [comment]
thanks a lot!! that's all I needed :)
