### ISSUE TITLE
Turkish Character Issue

### ISSUE THREAD

**Issue by alpergunay** [DevExpress/DevExtreme.AspNet.Data#272]
Hi, 
We are using your library in one of our projects and we found an issue about filtering grid. When we want to filter grid with using column filtering option, your library is converting filter criteria to lowercase by default. I think library is using English as default language for conversion. For example if we use upper case "I" in filter criteria, library is creating query with lowercase "i". But it is wrong in Turkish language. It should be converted to "ı" in Turkish. So if we use Turkish character in filter criteria, library is not getting any data. 
I am attaching a few screenshot. Let me know if you need any clarification. 
<img width="1192" alt="1" src="https://user-images.githubusercontent.com/25134503/42957696-1dfff964-8b8c-11e8-9c86-330d8b29abf8.png">
<img width="1206" alt="2" src="https://user-images.githubusercontent.com/25134503/42957695-1ddffdf8-8b8c-11e8-8c1c-2b91d32d4ef7.png">
<img width="1192" alt="3" src="https://user-images.githubusercontent.com/25134503/42957693-1dbf173c-8b8c-11e8-97ff-68fd1c35fd2d.png">

**Comment by AlekseyMartynov** [comment]
Hello

> I think library is using English as default language for conversion.

No, we use the [`String.ToLower`](https://docs.microsoft.com/en-us/dotnet/api/system.string.tolower) overload without arguments that takes into account the casing rules of the current culture (see [related code](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/c8dd5b345897a1d65ea0dc77f3c18f56f3f17558/net/DevExtreme.AspNet.Data/FilterExpressionCompiler.cs#L106-L126)).

However, the `ToLower` call that is applied to the property expression is handled by LINQ and is usually translated to SQL. For example: 
```sql
WHERE CHARINDEX('ı', LOWER(property)) > 0
```

So the are two parts:
1. The [`CurrentCulture`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo#Current) of .NET
2. The collation of database / table / specific columns

Ensure that both are properly set to Turkish. Then check if plain LINQ `Where` queries on your data source run fine. In this case, the library should work correctly, too.
