### ISSUE TITLE
DateTime conversion problem

### ISSUE THREAD

**Issue by alpergunay** [DevExpress/DevExtreme.AspNet.Data#275]
When we filter rows according to a datetime value, query generator is generating query with datetime2 value and this causes conversion error. For example when we filter row with 2018-07-30T00:00:00, at geneareted sql we see 2018-07-30T00:00:00.**0000000** and because of this sql returns error and filtering is not working.

**Comment by AlekseyMartynov** [comment]
Most probably, you need to specify the column SQL type at the LINQ provider level.
Example:
https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/b62c258a5a2c1c8710acb4097197da8d9d87073e/net/Sample/Models/Order.cs#L25-L29

**Comment by alpergunay** [comment]
Thank you Aleksey, adding type has solved my problem. As far as I understand I have to add SQL type for all datetime properties.
