### ISSUE TITLE
$select is limited to 32 items

### ISSUE THREAD

**Issue by jansokoly** [DevExpress/DevExtreme.AspNet.Data#284]
For some reason, there's [32 item limit](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/net/DevExtreme.AspNet.Data/Types/AnonType.Generated.cs#L402) to the array, which can be passed to $select and attempts to pass an array with more items consequently fail with "[Too many type arguments](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/net/DevExtreme.AspNet.Data/Types/AnonType.cs#L52)".

Why is it limited?

**Comment by AlekseyMartynov** [comment]
Indeed, 32 is the current max size of the [`AnonType` type family](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/net/DevExtreme.AspNet.Data/Types/AnonType.Generated.cs).
Related: #252, #254.

I think it's possible to remove this limitation in the [`RemoteSelect = false` mode](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/1f09ecdec373c520f0a93b31fc3b4a9a2693eaa5/net/DevExtreme.AspNet.Data/DataSourceLoadOptionsBase.cs#L73-L74) (currently if fails too).

If you're using a static set of properties for `select` then you can pre-select on server instead, as described in https://stackoverflow.com/a/49006427 (marked 'Best choice').

It would be helpful for us to know your scenaro, and whether or not the current limits are blocking.

**Comment by jansokoly** [comment]
Here's my scenario.

I display a grid, datasource of which is json generated on server. I need to apply authorization rules to control which user may see which grid columns.

That has 2 parts:
1. Not displaying them in UI.
That's the easy one, because it's just matter of adding or not adding to Columns collection based on server-side conditions.
```c#
@(Html.DevExtreme().DataGrid()
    .Columns(columns =>
    {
        if (SomeAuthorizationCondition)
        {
            columns.Add().DataField("foo");
        }
        columns.Add().DataField("bar");
    }
)
```

2. Not passing them in json from server.
To make sure tech-savvy users are not able to access data they're not supposed to see by looking into json reponse from server. I utilize `Select` to achieve that.
```c#
// Data projection to cope with json serialization.
var data = dataFromDatabase.Select(p => new
{
    foo = p.foo,
    bar = p.bar
}

// Get names of all anonymous object properties.
var selectedColumns = new List<string>();
foreach (var item in data.ElementType.GetProperties())
    selectedColumns.Add(item.Name);

// Remove those, this user has no permission to access.
if (!SomeAuthorizationCondition)
    selectedColumns.Remove("foo");

// Instruct DataSourceLoader to only select a subset of data.
options.Select = selectedColumns.ToArray();

return DataSourceLoader.Load(data, options);
```

It works just fine in cases, where the array passed to `Select` does not contain more than 32 items.

**Comment by jansokoly** [comment]
Thanks for suggestion, but that's only feasible if you have one or two such conditions, but having to cover all combinations if you have 30 or so is not.
I've reimplemented it since and send nulls in JSON as values of columns user has no access to. I would rather not send it at all, but that 32 limit makes it impossible.
