### ISSUE TITLE
Provide an option for case-insensitive string equality / inequality

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#296]
Requested by a user in https://github.com/DevExpress/DevExtreme.AspNet.Data/commit/d9ff0d070618abc2047a619d780cf4aca4f2379a

**Comment by jaiforyou** [comment]
thanks!

test case changes [99f64ea](https://github.com/jaiforyou/DevExtreme.AspNet.Data/commit/99f64eacc2bca63acde4af2047180b375020a558)

**Comment by AlekseyMartynov** [comment]
@jaiforyou 

Work in progress: #298 

Please try a CI build from
https://ci.appveyor.com/project/AlekseyMartynov/devextreme-aspnet-data/branch/to-lower/artifacts 
([Instructions](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/docs/using-ci-builds.md))

**Comment by jaiforyou** [comment]
Thanks!

What does CI build here, should I copy the highlighted NuGet package or
need to click on 'Current build', see screenshot below:
[image: image.png]

**Comment by AlekseyMartynov** [comment]
![ci](https://user-images.githubusercontent.com/4426185/46877559-d36ef980-ce49-11e8-993a-6e9fb39b7945.png)

**Comment by jaiforyou** [comment]
Thanks!

**Comment by AlekseyMartynov** [comment]
@jaiforyou 
Did you have a chance to test the build?
Does the new behavior meet your requirements?

**Comment by AlekseyMartynov** [comment]
Included in `2.0.0-rc2`

**Comment by jaiforyou** [comment]
Hi AlekseyMartynov,

Sorry for delay response, seems the case-insensitive string search with
equality / inequality working fine.

Thank You,
Jaiprakash Barnwal
