### ISSUE TITLE
I can not insert, delete or update data Web API Service.

### ISSUE THREAD

**Issue by Severanin** [DevExpress/DevExtreme.AspNet.Data#302]
Hello! I use in the project Dotnet Core 2.1.4 WebApi and Angular 6. I use devextreme-aspnet-data-nojquery. When loadUrl data is sent to the client, and when using insertUrl, updateUrl, deleteUrl, the data is not received by the server.

Client:

```
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { Api } from 'src/app/lib/_servers';
import CustomStore from 'devextreme/data/custom_store';
import { createStore } from 'devextreme-aspnet-data-nojquery';

@Component({
  selector: 'app-building',
  templateUrl: './building.component.html',
  styleUrls: ['./building.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class BuildingComponent  {
  masterDetailDataSource: any;
  dataSource: CustomStore;

  constructor() {

    this.dataSource = createStore({
      key: 'id',
      loadUrl: Api.uavr + '/JBuilding/load',
      insertUrl: Api.uavr + '/JBuilding/InsertJBuilding',
      updateUrl: Api.uavr + '/JBuilding/UpdateJBuilding',
      deleteUrl: Api.uavr + '/JBuilding/DeleteSection',

      onBeforeSend: function(method, ajaxOptions) {
        const jwt = JSON.parse(localStorage.getItem('currentUser'));
        ajaxOptions.xhrFields = { withCredentials: true };
        ajaxOptions.headers = { 'Authorization': 'Bearer ' + jwt.token };

        console.log(ajaxOptions);
      }
    });
  }
}
```

Server

        [HttpPut("UpdateJBuilding")]

        public IActionResult UpdateJBuilding(int key, string values)
        {
            var section = _uavr.Jbuilding.FirstOrDefault(o => o.Id == key);
            if (section == null)
                return StatusCode(409, "Ошибка, раздел не найден");
            JsonConvert.PopulateObject(values, section);

            if (!TryValidateModel(section))
                return BadRequest(ModelState.ToFullErrorString());

            _uavr.SaveChanges();

            return Ok();
        }

        [HttpPost("InsertJBuilding")]

        public IActionResult InsertJBuilding(string values)
        {
            var newJBuilding = new Jbuilding();

            JsonConvert.PopulateObject(values, newJBuilding);

            if (!TryValidateModel(newJBuilding))
                return BadRequest(ModelState.ToFullErrorString());

            _uavr.Jbuilding.Add(newJBuilding);
            _uavr.SaveChanges();

            return Ok();
        }

        [HttpDelete("DeleteSection")]
        public IActionResult DeleteSection(int key)
        {
            var jBuilding = _uavr.Jbuilding.FirstOrDefault(o => o.Id == key);
            // if (jBuilding == null)
            //     return StatusCode(409, "Раздел не найден");

            _uavr.Jbuilding.Remove(jBuilding);
            _uavr.SaveChanges();

            return Ok(key);
        }

![image](https://user-images.githubusercontent.com/17942764/47618110-032c2b80-daf1-11e8-8bbd-1d82a8461b23.png)
![image](https://user-images.githubusercontent.com/17942764/47618174-c44aa580-daf1-11e8-9586-74435341ab1f.png)
![image](https://user-images.githubusercontent.com/17942764/47618182-e6dcbe80-daf1-11e8-8093-22197ee03c9f.png)

**Comment by AlekseyMartynov** [comment]
Hello

This may be due to overwriting `headers` and `xhrFields` in
```js
ajaxOptions.xhrFields = { withCredentials: true };
ajaxOptions.headers = { 'Authorization': 'Bearer ' + jwt.token };
```

Solution: https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/223#issuecomment-377502458

**Comment by Severanin** [comment]
Hello! did not help! 
ajaxOptions.xhrFields = { withCredentials: true };
//ajaxOptions.headers = { 'Authorization': 'Bearer ' + jwt.token }; ---> comment this line


![image](https://user-images.githubusercontent.com/17942764/47650188-43e37d80-dba1-11e8-9b35-dffd04376fbc.png)

**Comment by Severanin** [comment]
this.dataSource = createStore({
      key: 'id',
      loadUrl: Api.uavr + '/JBuilding/load',
      insertUrl: Api.uavr + '/JBuilding/InsertJBuilding',
      updateUrl: Api.uavr + '/JBuilding/UpdateJBuilding',
      deleteUrl: Api.uavr + '/JBuilding/DeleteSection',

      onBeforeSend: function(method, ajaxOptions) {
        const jwt = JSON.parse(localStorage.getItem('currentUser'));
        ajaxOptions.xhrFields = { withCredentials: true };
        console.log(ajaxOptions);
      }
    });

![image](https://user-images.githubusercontent.com/17942764/47661279-8bc2ce80-dbba-11e8-8eb7-f1ed81fc8658.png)

**Comment by AlekseyMartynov** [comment]
`Access-Control-Allow-Origin` errors indicate that you need to configure CORS:
https://docs.microsoft.com/en-gb/aspnet/core/security/cors?view=aspnetcore-2.1

**Comment by Severanin** [comment]
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddAutoMapper(x => x.AddProfile(new AutoMapperProfile()));  


            // services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services.AddMvc();

            services.AddDbContext<UavrDbContext>(options => options.UseSqlite("Data Source=DataBase/Uavr.db"));
            services.AddDbContext<SecurityDbContext>(options => options.UseSqlite("Data Source=DataBase/Security.db"));

            var appSettingsSection = Configuration.GetSection("AppSettings");
            services.Configure<AppSettings>(appSettingsSection);

            // настройка jwt аутентификации
            var appSettings = appSettingsSection.Get<AppSettings>();
            var key = Encoding.ASCII.GetBytes(appSettings.Secret);

            services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(x =>
            {
                x.RequireHttpsMetadata = false;
                x.SaveToken = true;
                x.TokenValidationParameters = new TokenValidationParameters
                {
                    // валидация ключа безопасности
                    ValidateIssuerSigningKey = true,
                    // установка ключа безопасности
                    IssuerSigningKey = new SymmetricSecurityKey(key),
                    // укзывает, будет ли валидироваться издатель при валидации токена
                    ValidateIssuer = false,
                    // установка потребителя токена
                    ValidateAudience = false,
                    // будет ли валидироваться время существования
                    // ValidateLifetime = true,
                };
            });
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseCors(x => x
                .AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials());

            if (env.IsDevelopment())
            {
                app.UseDatabaseErrorPage();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }
            app.UseAuthentication();
            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseMvc();
        }
    }
}

**Comment by Severanin** [comment]
CORS add to Server project, and add allow AllowAnyOrigin, AllowAnyMethod, AllowAnyHeader, AllowCredentials.

**Comment by AlekseyMartynov** [comment]
Ok. Another thing to check is the spelling of the key (`id` vs `Id` vs `ID`). Also ensure that the key property is present in the response of the `load` action.

Without debugging, I don't have other ideas.
If possible, please share your project with us by submitting a private [support ticket](https://devexpress.com/sc).

**Comment by Severanin** [comment]
T685999

**Comment by Severanin** [comment]
What is the problem?

**Comment by sometimesElen** [comment]
Hi,
Thank you for creating a ticket in our Support Center. We need additional time to research it.

We also kindly ask you to continue our communication in the context of the [T685999](https://isc.devexpress.com/Thread/WorkplaceDetails?id=T685999) thread. Feel free to contact us there if you have any further questions.
