### ISSUE TITLE
Support async ??

### ISSUE THREAD

**Issue by pilouk** [DevExpress/DevExtreme.AspNet.Data#308]
Does the load function support async and can return an task action result?

**Comment by AlekseyMartynov** [comment]
In async actions, create a `Task` manually:

```c#
public Task<object> Orders(DataSourceLoadOptions loadOptions) {
    return Task.FromResult<object>(DataSourceLoader.Load(_nwind.Orders, loadOptions));
}
```

```c#
public Task<object> Orders(DataSourceLoadOptions loadOptions) {
    return Task.Run<object>(() => DataSourceLoader.Load(_nwind.Orders, loadOptions));
}
```

```c#
public Task<IActionResult> Orders(DataSourceLoadOptions loadOptions) {
    return Task.Run<IActionResult>(() => Content(
        JsonConvert.SerializeObject(DataSourceLoader.Load(_nwind.Orders, loadOptions)),
        "application/json"
    ));
}
```

Currently, there is no built-in support for async in the library.

**Comment by MateuszBogdan** [comment]
That is a really big issue!! Provided answer does not really help since it is an antipattern - Sync over async. This library really need async overloads. Please look into this and reopen the ticket.

**Comment by AlekseyMartynov** [comment]
Hello @MateuszBogdan

I agree that fake async is an anti-pattern.
However, to implement a generic API that is truly async down to the database, we need something like `IAsyncQueryable` (https://github.com/dotnet/corefx/issues/34161, https://github.com/dotnet/roslyn/issues/32569) along with proper support in LINQ providers.

Today, async query methods, such as `CountAsync`, are provider-specific:
- [EF6 `QueryableExtensions`](https://github.com/aspnet/EntityFramework6/blob/6.2.0/src/EntityFramework/QueryableExtensions.cs)
- [EF Core `QueryableExtensions`](https://github.com/aspnet/EntityFrameworkCore/blob/v2.2.2/src/EFCore/Extensions/Internal/QueryableExtensions.cs)
- [NHibernate `LinqExtensionMethods`](https://github.com/nhibernate/nhibernate-core/blob/5.2.3/src/NHibernate/Linq/LinqExtensionMethods.cs)

Did you encounter a real-life case in which the lack of async becomes a bottleneck? What is the workload type (Web API, etc)?

**Comment by AlekseyMartynov** [comment]
**P.S.** Despite aforementioned limitations, I filed a new ticket #337.
We'll research whether it's possible to take advantage of existing async capabilities.

**Comment by pwen090** [comment]
I am looking to switch from Telerik to DevExpress. Their ToDataSourceResult() method seems to support async. Is there a reason that they are able to do it and not DevExpress? Is it because you work with more systems or something? Maybe a review of their code to see how they do it? thank you, DevExpress is looking like a nice alternative.

**Comment by AlekseyMartynov** [comment]
@pwen090 

We'll add support for async very soon. It's currently work in progress. Subscribe to #337 to be notified when it's released.

Thank you!
