### ISSUE TITLE
HttpInterceptor with DevExtreme.AspNet.Data doesn't work Angular 6

### ISSUE THREAD

**Issue by pilouk** [DevExpress/DevExtreme.AspNet.Data#309]
Angular 6 here
HttpInterceptor doesn't intercept the call from the  DevExtreme.AspNet.Data 
The token is not added to the query

Do you guys use HttpClient ?

Must use HttpClient since angular 4.3+

**Comment by pilouk** [comment]
Added a ticket on dev extreme : [https://www.devexpress.com/Support/Center/Question/Details/T695057/example-for-custom-data-source-using-filter-property](url)

**Comment by AlekseyMartynov** [comment]
Hello @pilouk 

Indeed, currently there's no way to use Angular's HTTP API for AJAX requests.
We plan to improve this (#311).

Here is how you can solve two typical tasks without the use of `HttpInterceptor`.

### Customize a request (URL, headers, query string, HTTP verb)

```js
import * as AspNetData from "devextreme-aspnet-data-nojquery";

const store = AspNetData.createStore({
  // . . .

  onBeforeSend: (operation, ajaxOptions) => {
    ajaxOptions.headers = {
      "Authorization": "..."
    };
  }
});
```

The members of `ajaxOptions` are available in the [TypeScript declaration](https://unpkg.com/devextreme-aspnet-data-nojquery@2.0.0/index.d.ts).

### Redirect to a login form upon receiving `Unauthorized` response

```js
store["_errorHandler"] = (e: Error) => {
  if (e.message.indexOf("Unauthorized") > -1)
    location.href = "/login";
};
```

Related: #297, #310
