### ISSUE TITLE
RemoteAvgAgregator throws InvalidCastException

### ISSUE THREAD

**Issue by coeamyd** [DevExpress/DevExtreme.AspNet.Data#324]
Dear DevExtreme team,

we are using the DevExtreme.AspNet.Data library to deliver data to the dxDataGrid. We are now introducing group summaries and have hit an issue, that is most likely the same issue as with #182 (AVG summary caluclation is broken for Double data after #148). The fix for that issue fixed it only for local grouping and summaries, not for remote grouping.

The problem turns up in DevExtreme.AspNet.Data/RemoteGrouping/RemoteAvgAggregator.cs:line 28, where it tries to cast the result of the sum aggregator to a nullable decimal.

    return (decimal?)_valueAggregator.Finish() / count;

Since the value returned by `Finish` is boxed, a direct cast will lead to the InvalidCastException. We have been able to fix it by replacing that line with

    var val = this._valueAggregator.Finish();
    return val == null ? null : Convert.ToDecimal(val) / count;

We are, however, not sure if this is the optimal solution. Will you be able to supply an official fix for this?

Thanks for the good work on your products!

Cheers,
Christoph

**Comment by AlekseyMartynov** [comment]
Thanks for reporting and debugging the issue.
I'm working on a fix.

**Comment by AlekseyMartynov** [comment]
Please try an intermediate NuGet from
https://ci.appveyor.com/project/dxrobot/devextreme-aspnet-data/builds/21525681/artifacts

The procedure of installing CI builds is described in [Using CI Builds](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/docs/using-ci-builds.md#nuget-package)

**Comment by coeamyd** [comment]
The fix looks like it's working. Thanks for the fast response!

Keep up the good work :-)

**Comment by AlekseyMartynov** [comment]
We've just published [2.1.1](https://github.com/DevExpress/DevExtreme.AspNet.Data/releases/tag/2.1.1)
NuGet: https://www.nuget.org/packages/DevExtreme.AspNet.Data/2.1.1

**Comment by coeamyd** [comment]
Perfect, thanks a lot!
