### ISSUE TITLE
Add handler for "onAfterSend"

### ISSUE THREAD

**Issue by Mik4sa** [DevExpress/DevExtreme.AspNet.Data#329]
Hello DevExpress,

for a project I need to have access to the generated xhr object.
I'm talking about the response from this call:
https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/c8e044f6d02a196a7bed83443fd4095126b49056/js/dx.aspnet.data.js#L67

Directly after it is created. Something like a "onAfterSend" event.
Knowing by which operation it was created is also necessary for this project. Since I want to process them only, if it was created by a load operation.

Is there a way that you (or me by a pull request?) can add this?

Sincerely,
Kai

**Comment by AlekseyMartynov** [comment]
Hello

If you are using the jQuery version of the client script you can intercept XHR objects via [jQuery AJAX events](https://api.jquery.com/Ajax_Events/).

#311 seems related.

**Comment by Mik4sa** [comment]
Actually we are using it in an angular app without jQuery.
Even though, I wouldn't know the actual load operation. Whether it's "load", "update", "insert" or "delete"

**Comment by AlekseyMartynov** [comment]
Got you.
We'll prioritize #311. Please subscribe to that ticket.

For now, please use a manually-patched version of the script.
