### ISSUE TITLE
handleInsertUpdateSuccess json.parse where res already parsed to object

### ISSUE THREAD

**Issue by PedroS5499** [DevExpress/DevExtreme.AspNet.Data#333]
When insert new record to datagrid, server response in json. in the dx.aspnet.data.js line 156
d.resolve, check if mime is JSON (and that is true) but res already parsed as object, so when try to json.parse again return exception.

i had to fix that: 

```js
function handleInsertUpdateSuccess(d, res, xhr) {
    var mime = xhr.getResponseHeader("Content-Type"),
        isJSON = mime && mime.indexOf("application/json") > -1;
    d.resolve(isJSON && typeof res === "string" ? JSON.parse(res) : res);
}
```

**Comment by AlekseyMartynov** [comment]
How can I reproduce this?
Insert requests are executed with `dataType=text`, therefore response objects are not automatically parsed.

https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/e3c3e88ecdf4c18acc90f858118e0e692c32ca7c/js/dx.aspnet.data.js#L57-L62
