### ISSUE TITLE
How to modify loadResult when grouping

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme.AspNet.Data#338]
Hi,

I need to modify loadResult data to set some fields after filtering (for ex.: I need to get Product with it's actual and previous price. So, I need to get all products, call Load() to filter data and then find the previous price). Of cource, I can set data before calling Load method, but what if I need just 10 Products, but I need to set previouse price for all products, which cause some perfomance issues. 

As I can see, I can modify LoadResult.data when there is no grouping, but how to modify result with grouping?

**Comment by AlekseyMartynov** [comment]
>  if I need just 10 Products, but I need to set previouse price for all products, which cause some perfomance issues.

Is is possible to add a lazy-evaluated computed property?

```c#
[NotMapped]
public decimal PrevPrice {
    get { return FigureOutPrevPrice(...); }
}
```

> As I can see, I can modify LoadResult.data when there is no grouping, but how to modify result with grouping?

What is the exact problem you have encountered?

**Comment by Bykiev** [comment]
> >Is is possible to add a lazy-evaluated computed property?
> 
Unfortunately, no, because this prtopery is calculated with recursive function

> > As I can see, I can modify LoadResult.data when there is no grouping, but how to modify result with grouping?
> 
> What is the exact problem you have encountered?
As I can see, LoadRuslt data property can be dyncamic, expando object or collection of type Group. So, when the dxDataGrid was grouped by some field it makes 2 request, on the second requests data where I can modify data property after call Load method. 

The real issue is export data to excel, it makes only 1 request and Result data type is collection of  Group and I don't see the actual Product objects. Remote paging and grouping are enabled.

**Comment by Bykiev** [comment]
@AlekseyMartynov, sorry, closed by mistake

**Comment by Bykiev** [comment]
Ended up with this recusrsive method:
```
private List<Product> GetData(object data, List<Product> objects)
        {
            if (objects == null)
                objects = new List<Product>();

            var collection = data as IEnumerable<object>;

            if (collection != null)
            {
                foreach (var item in collection)
                {
                    var r = item as Product;

                    if (r != null)
                        objects.Add(r);
                    else
                    {
                        var group = item as Group;
                        if (group != null && group.items != null)
                        {
                            foreach (var it in group.items)
                            {
                                var f = it as Product;
                                if (f != null)
                                    objects.Add(f);
                                else
                                {
                                    if (it is Group)
                                    {
                                        var g = it as Group;
                                        return GetModels(g, objects);
                                    }
                                }
                            }
                        }
                    }
                }
            }

            return objects;
        }
```

**Comment by statler** [comment]
I have a generic method that may help here. I use it like this in my controllers specifically for my projections as described in https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/367#issuecomment-573893506.

The translator is any method accepting a List of the projected type, and returning the same. Should be pretty easy to modify for any other purpose.

        public async Task<IActionResult> GetEntitiesForProjectAsync<TDto>(DataSourceLoadOptions loadOptions, Func<List<TDto>, Task<List<TDto>>> translator) where TDto : class
        {
            var ProjectEntities = await GetLoadResultForProjectAsync<TDto>(loadOptions);//<=just a call to DataSourceLoader.LoadDtoAsync - refer https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/367#issuecomment-573893506
            if (ProjectEntities is LoadResult lr && lr.data is IEnumerable data)
            {
                lr.data = await TranslateLoadResultDataAsync<TDto>(data, translator);
                return Ok(lr);
            }
            return new OkObjectResult(ProjectEntities);
        }

The method

	public async Task<IList> TranslateLoadResultDataAsync<TDto>(IEnumerable lstData, Func<List<TDto>, Task<List<TDto>>> translator)
        {
            if (lstData == null) return null;
            if (lstData is IEnumerable<T> lstBaseTypeData)
            {
                lstData = _mapper.Map<List<T>, List<TDto>>(lstBaseTypeData.ToList());
            }
            if (lstData is IEnumerable<TDto> lstDtoTypeData)
            {
                var lst = lstDtoTypeData.ToList();
                return await translator(lst);
            }
            if (lstData is IEnumerable<Group> lstGroupData)
            {
                var lst = lstGroupData.ToList();
                foreach (Group group in lst)
                {
                    group.items = (await TranslateLoadResultDataAsync<TDto>(group.items, translator));
                }
                return lst;
            }
            //any other case
            var lstObject = new List<object>();
            foreach (object o in lstData)
            {
                lstObject.Add(o);
            }
            return lstObject;
        }

**Comment by krptodr** [comment]
@statler The code snippets above, aren't complete. Can you please revise?

**Comment by statler** [comment]
@krptodr 

Please be more specific about what you think is missing. I am pretty sure everything is there, or referenced as described by the comment to #367 for GetLoadResultForProjectAsync

**Comment by krptodr** [comment]
@statler I can’t piece the two tickets together. I think that function is missing. Do you have an example you can provide in DevExpress example format? I’d really appreciate leveraging you’re idea from ticket #367 and here for the grouping.

**Comment by statler** [comment]
If someone can give me a clean working basic webapi asp.net core 2 project (no asp.net views - just the webapi) for the northwind db with entity framework .core 2, I will have a chop at it. The devex examples are not .Net Core, and not really relevant to this.
