### ISSUE TITLE
Support comparison operations (<, >, etc) for Guid

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#339]
![microsoftteams-image](https://user-images.githubusercontent.com/4426185/53737148-c4422400-3e9c-11e9-8bfb-c4e160cf3f17.png)

**Comment by Dmitry-Ostashev** [comment]
When the user clicks the grid column header for the sorting, the dxDataGrid generates loadOptions with with a filter. This filter contains a condition for the key field which can have the Guid type.
![image](https://user-images.githubusercontent.com/24777868/53739473-e3dc4b00-3ea2-11e9-99b9-92ef7923e99c.png)
