### ISSUE TITLE
Custom server summaries throw System.NotSupportedException: 'Specified method is not supported.' after update Microsoft.AspNetCore.All from 2.1.6 to 2.2.0

### ISSUE THREAD

**Issue by maxima-net** [DevExpress/DevExtreme.AspNet.Data#340]
The sample project is here
https://www.dropbox.com/s/4k58fbplpdkouyf/cu-final.zip?dl=0
(PS: the sample project is based on https://github.com/aspnet/Docs/tree/a04a213efd56fbaa66eb18ba2868e904ba114a18/aspnetcore/data/ef-mvc/intro/samples/cu-final)

Steps to reproduce: just run the project, the exception will be thrown;

After these changes we have got the issue:
![image](https://user-images.githubusercontent.com/28503437/53869069-8104c400-4008-11e9-9d49-db8eb5a98c77.png)

The exception:
![image](https://user-images.githubusercontent.com/28503437/53869460-5b2bef00-4009-11e9-8c42-fe798b606395.png)

The stack trace:
![image](https://user-images.githubusercontent.com/28503437/53869733-d55c7380-4009-11e9-9929-75c4c9804003.png)

The grid configuration:
![image](https://user-images.githubusercontent.com/28503437/53869512-73037300-4009-11e9-9a70-fab77027bb1c.png)

The aggregator + its registration:
![image](https://user-images.githubusercontent.com/28503437/53869597-99291300-4009-11e9-9794-e9da754f8345.png)

**Comment by AlekseyMartynov** [comment]
Привет, Макс 😈

**Comment by AlekseyMartynov** [comment]
Приходи фиксить будем :)

**Comment by AlekseyMartynov** [comment]
`CustomAggregators` only work with `RemoteGrouping = false`
It's mentioned in the [docs](https://devexpress.github.io/DevExtreme.AspNet.Data/net/api/DevExtreme.AspNet.Data.Aggregation.CustomAggregators.html).

`RemoteGrouping` defaults to `false` in 2.1 and to `true` in 2.2.
Hence the exception.

https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/3eb32ba21a1e44626509508d7fd4e1d3e59c89d3/net/DevExtreme.AspNet.Data/DataSourceLoadContext.cs#L81-L86

**Comment by maxima-net** [comment]
@AlekseyMartynov Ok, thank you.

Should the flag be set in a controller? Like that:
![image](https://user-images.githubusercontent.com/28503437/53873182-d47b1000-4010-11e9-8416-27cc8ee6bb0b.png)

Or the best way is to set this in a grid settings? But I could not find the convenient way to set all remote opperations except of grouping;

**Comment by maxima-net** [comment]
By the way the following approach does not fix the exception (but the previous approach works well):
![image](https://user-images.githubusercontent.com/28503437/53874140-d80f9680-4012-11e9-889f-283a80d9e3a9.png)

**Comment by AlekseyMartynov** [comment]
These are different options.
Grid's options enable remote data processing.
[`DataSourceLoadOptions.RemoteGrouping`](https://devexpress.github.io/DevExtreme.AspNet.Data/net/api/DevExtreme.AspNet.Data.DataSourceLoadOptionsBase.html#DevExtreme_AspNet_Data_DataSourceLoadOptionsBase_RemoteGrouping) is specific to this library.

Based on your feedback, I created a ticket #341 to improve the error message.

**Comment by maxima-net** [comment]
> These are different options.
> Grid's options enable remote data processing.
> [`DataSourceLoadOptions.RemoteGrouping`](https://devexpress.github.io/DevExtreme.AspNet.Data/net/api/DevExtreme.AspNet.Data.DataSourceLoadOptionsBase.html#DevExtreme_AspNet_Data_DataSourceLoadOptionsBase_RemoteGrouping) is specific to this library.
> 
> Based on your feedback, I created a ticket #341 to improve the error message.


Thank you for the clarification;


So this fix is the best practice for the described case: 
> @AlekseyMartynov Ok, thank you.
> 
> Should the flag be set in a controller? Like that:
> ![image](https://user-images.githubusercontent.com/28503437/53873182-d47b1000-4010-11e9-8416-27cc8ee6bb0b.png)
> 
> Or the best way is to set this in a grid settings? But I could not find the convenient way to set all remote opperations except of grouping;

@AlekseyMartynov approve the fix, please.
And if you approve, the issue can be closed;
