### ISSUE TITLE
DevExtreme.AspNet.Data (client): filter specified via loadParams not working

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme.AspNet.Data#348]
I'd like to predefine filter on a dataSource (e.g. display data of current date). When filter specified via loadParams an error occured because for loadParams JSON.stringify() is not called and even though it will not applied becuse of this line of code:
`$.extend(result, loadParams);`

My code:
```
dataSource: DevExpress.data.AspNet.createStore({
    loadUrl: "api/Orders",
    loadParams: {
          filter: ["Date", ">=", moment(new Date()).format('YYYY-MM-DD')]
     }
}),
```

Is it a bug or I'm doing smth wrong?

**Comment by AlekseyMartynov** [comment]
Adding `JSON.stringify` should fix it.

```js
loadParams: {
    filter: JSON.stringify(["Date", ">=", moment(new Date()).format('YYYY/MM/DD') ])
}
```

However, this unconditionally overwrites any filter passed to the `load` call.

Alternatively, you can extend the filter in `onBeforeSend` ([docs](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/docs/client-side-with-jquery.md#api-reference)), or use a preliminary `.Where` LINQ on the server side.

**Comment by Bykiev** [comment]
@AlekseyMartynov, thanks, it'll be better if JSON.stringify will'be applyed inside client library, also filter shouldn't override other filters. Now it's not documented and looking like a bug.

**Comment by AlekseyMartynov** [comment]
> Now it's not documented and looking like a bug.

Per our docs, `loadParams` are 
> **additional** parameters that should be passed to `loadUrl`

They are not intended to override the standard load options such as `sort` or `filter`.
Their serialization is handled by the underlying AJAX implementation (e.g. https://api.jquery.com/jQuery.param).

**Comment by Bykiev** [comment]
@AlekseyMartynov, thx! It confused me because client library is just and implementation of CustomStore and I expected it will be implemented.

**Comment by AlekseyMartynov** [comment]
The question seems to be resolved.
Closing.
