### ISSUE TITLE
There is already an open DataReader associated with this Command which must be closed first

### ISSUE THREAD

**Issue by LadislavSopko** [DevExpress/DevExtreme.AspNet.Data#352]
Hello.
I just clone repo,  I did change connection string ("Data Source=localhost;Initial Catalog=Northwind;User ID=test;Password=test;MultipleActiveResultSets=True"), 
then I run console version and got almost on each run this exception:
'There is already an open DataReader associated with this Command which must be closed first'
In : AgregateCalculator.cs, line: 39
I did try to add in connection string: 'MultipleActiveResultSets=True' but it won't even start. There is other exception then: 'System.InvalidCastException: Unable to cast object of type 'System.Data.ProviderBase.DbConnectionClosedConnecting' to type 'System.Data.SqlClient.SqlInternalConnectionTds'

Regards
ladislav

**Comment by AlekseyMartynov** [comment]
Hello

What does `dotnet --version` tell?

The mentioned `InvalidCastException` is discussed in the following threads:
- https://stackoverflow.com/q/46138168
- https://github.com/aspnet/EntityFrameworkCore/issues/11595
- https://social.msdn.microsoft.com/Forums/en-US/2602a87c-a123-47ad-8f82-961df495e8dc/
