### ISSUE TITLE
Host it on cdn, or better, on cdnjs

### ISSUE THREAD

**Issue by MihaMarkic** [DevExpress/DevExtreme.AspNet.Data#354]
As per title, it'd be really helpful if it was hosted on either cdnjs (better) or at least cdn.

**Comment by AlekseyMartynov** [comment]
Hi Miha
Since the library is on NPM, you can use [UNPKG](https://unpkg.com/):
https://unpkg.com/devextreme-aspnet-data@2.2.1/js/dx.aspnet.data.js

**Comment by MihaMarkic** [comment]
@AlekseyMartynov  Thanks, but I'm a bit confused by DX distribution. DevExtreme is on unpkg but it's not official (AFAIK) and it certainly doesn't work.
So, is this an officially supported source that works with libman/VS?

**Comment by AlekseyMartynov** [comment]
> DevExtreme is on unpkg but it's not official (AFAIK) and it certainly doesn't work.

We use UNPKG in many DevExtreme online demos. As an example, check `config.js` in [Angular demos](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/WebAPIService/Angular/Light/). It works fine. According to UNPKG homepage, their CDN is backed by Cloudflare and Google Cloud.

>  is this an officially supported source that works with libman/VS?

Yes, UNPKG is one of the LibMan built-in providers ([docs](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-cli)).

**Comment by AlekseyMartynov** [comment]
Related Support ticket:
https://devexpress.com/issue=T578443

**Comment by AlekseyMartynov** [comment]
Another public CDN for NPM:
https://cdn.jsdelivr.net/npm/devextreme-aspnet-data@2.5.0/js/dx.aspnet.data.js

[How does it work?](https://www.jsdelivr.com/network/infographic)

**Comment by AlekseyMartynov** [comment]
Finally on cdnjs 🎉 
https://cdnjs.com/libraries/devextreme-aspnet-data
