### ISSUE TITLE
Please add support onError action/event in server side code

### ISSUE THREAD

**Issue by hype11** [DevExpress/DevExtreme.AspNet.Data#359]
There is no action/event to handle errors in a custom way at server side.
There is a property "Log" (in Devart.Data.Linq.DataContext) for logging statements etc. but nothing which is fired in error case.

**Comment by AlekseyMartynov** [comment]
You can catch and handle server errors using a `try-catch` block:

```c#
try {
    // Use DataSourceLoader
} catch(Exception x) {
    // handle the error
}
```

**Comment by hype11** [comment]
I use it in this way:
DataSourceLoader.Load(IQueryable, DataSourceLoadOptions)
The IQueryable is executed out of controller scope, so I cannot add a simple try-catch, because the IQueryable is executed in DevExpress logic or while serializing.
I hope it's understandable.

**Comment by AlekseyMartynov** [comment]
Now I understand that you need to catch exceptions that occur during the delayed enumeration of the result.

Possible solutions:

#### 1. Force JSON serialization
```c#
var loadResult = DataSourceLoader.Load(source, loadOptions);
try {
    return Content(JsonConvert.SerializeObject(loadResult), "application/json");
} catch(Exception x) {
    // TODO
    throw;
}
```
#### 2. Force enumeration (feature request #347)
```c#
var loadResult = DataSourceLoader.Load(source, loadOptions);
try {
    loadResult.data = loadResult.data.Cast<Object>().ToArray();
    return loadResult;
} catch(Exception x) {
    // TODO
    throw;
}
```

**Comment by hype11** [comment]
Thank you for your help. I implemented the executing of the Queryable. In my case I could not execute the query in all cases, because the "IsCountQuery"-request throws an exception. So in future, it would be nice to have a possiblity to add a logger function.

**Comment by AlekseyMartynov** [comment]
Thank you. I updated the code snippets. Now they handle `IsCountQuery` errors, too.
