### ISSUE TITLE
Handling of large long values broken in JS

### ISSUE THREAD

**Issue by coeamyd** [DevExpress/DevExtreme.AspNet.Data#386]
Dear DevExtreme support team,

we are currently having issues with data being returned from the DxAspNetData service not being handled correctly on the client side. We have a column with Int64 (long) values, which tend to get quite large. These numbers actually go past Number.MAX_SAFE_INTEGER (9007199254740991), which is why the numbers become only approximations.

To work around the issue, we have already changed our result being returned to be a string instead of a long, since you cannot change the number handling of javascript. We did this by modifiying the result being returned after the `DataSourceLoader.Load(query, loadOptions)` call. However, this only applies to the actual grid data. We have now added a header filter, and since it returns a different type of result, a more generalized handling becomes necessary.

I would like to propose a load option `Int64AsStringFormat`, which, when set, will automatically format any Int64 values to string according to the specified value. Do you think, this makes sense as a general load option? Then, I would try implementing it in a fork. Otherwise, I will add this fix only in our solution.

Thanks for your feedback!

Cheers,
Christoph

**Comment by AlekseyMartynov** [comment]
Hello

Alternatively, this can be solved on the JSON serialization level:

```c#
class LongNumberToStringConverter : JsonConverter {
    public override bool CanConvert(Type objectType) {
        return objectType == typeof(long)
            || objectType == typeof(long?)
            || objectType == typeof(decimal)
            || objectType == typeof(decimal?);
    }

    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) {
        throw new NotImplementedException();
    }

    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
        writer.WriteValue(Convert.ToString(value));
    }
}
```

```c#
var source = new[] {
    new { n1 = Int64.MaxValue, n2 = decimal.MaxValue }
};

var loadResult = DataSourceLoader.Load(source, new DataSourceLoadOptionsBase());

var json = JsonConvert.SerializeObject(loadResult, new LongNumberToStringConverter());
// {"data":[{"n1":"9223372036854775807","n2":"79228162514264337593543950335"}]}

return Json(json);
```

A load option makes sense though it seems to be the first time this topic is raised. We can keep the ticket open to gather more feedback.

> Dear DevExtreme support team,

Actually, the support is at https://devexpress.com/sc but you're welcome here at GitHub too.

**Comment by coeamyd** [comment]
> Actually, the support is at https://devexpress.com/sc but you're welcome here at GitHub too.

I thought, since this affects the AspNet.Data component, I'd be better off here. Also, since this isn't my first issue raised here, I knew responses here are faster than in the DevExpress support. I'm not saying, the official support is slow, you're just much faster. Kudos for that :-)

Good idea with the change on json serialization level. I think, I'll rework my code to use this mechanism. It seems the cleaner approach.
