### ISSUE TITLE
Using DataSourceLoader with custom sort

### ISSUE THREAD

**Issue by MihaMarkic** [DevExpress/DevExtreme.AspNet.Data#388]
For various reasons, I want to pass an IQueryable<T> containing an OrderBy statement to DataSourceLoader.Load.

Basicallly something like 

```csharp
var items = db.Items.OrderBy(i => i.Name).Select(i => i.Name);

 // where loadOptions.Sort = new SortingInfo[0];
var result = DataSourceLoader.Load(items, loadOptions);
```

When working with version 2.4.4  ~~Load did honor the OrderBy~~, but 2.5.0 ignores it completely (both ignore it actually). So, how I go with custom sorting in this case?

**Comment by AlekseyMartynov** [comment]
You can use the [DataSourceLoadOptionsBase.DefaultSort](https://devexpress.github.io/DevExtreme.AspNet.Data/net/api/DevExtreme.AspNet.Data.DataSourceLoadOptionsBase.html#DevExtreme_AspNet_Data_DataSourceLoadOptionsBase_DefaultSort) property or build a custom sort list:

```c#
var mySort = . . .;
loadOptions.Sort = mySort; 
```

The following support ticket may be relevant:
- https://devexpress.com/issue=T657002

**Comment by MihaMarkic** [comment]
@AlekseyMartynov Well, that most probably won't work if I were to use a client side projection.

**Comment by AlekseyMartynov** [comment]
Would you please add a code sample to illustrate what exactly won't work?

Internally, `DataSourceLoader` builds a LINQ expression by appending `Where`, `OrderBy`, etc to the source query. For example:

```c#
db.Items.OrderBy(i => i.Name).Select(i => i.Name)
    .Where(...)
    .OrderBy(...)
```

Subsequent `OrderBy` cancels previous `OrderBy`. To keep sorting by `Name`, you can use `DefaultSort` or modify `Sort` as suggested in https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/388#issuecomment-537113787.

Alternatively, we can add a boolean option to prevent any sort inside `DataSourceLoader` when the source query is pre-sorted.

**Comment by MihaMarkic** [comment]
@AlekseyMartynov  Sorry for the delay

Imagin a projection to a 

```csharp
class ClientSide {
  public string LowercaseName { get; set; }
}

DataSourceLoader.Load(db.Items.Select(i => new ClientSide { LowercaseName = string.ToLower(i.Name) } , loadOptions});
```

Perhaps I'm wrong, but Select in this case is client side and applying sort and/or filter on it, would cause a problem because it will have to fetch all the data from the database first.

**Comment by AlekseyMartynov** [comment]
Thank you for the update. Now I better understand the issue. You need to sort original items by `Name` and then project them so that `Name` becomes `LowercaseName`.

I just posted a [comment about DTO mapping](https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/367#issuecomment-543713028). Please review it and let me know if such a feature would address your requirements. In the interim, check if you can use the workaround suggested in https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/378#issuecomment-531978173.
