### ISSUE TITLE
Creating a custom filter using RegisterBinaryExpressionCompiler for complex, runtime compiled where clause

### ISSUE THREAD

**Issue by statler** [DevExpress/DevExtreme.AspNet.Data#392]
I started writing an issue around how to directly add a complex where clause using the RegisterBinaryExpressionCompiler because I couldn't get the damned thing to work. In the end I figured it out and though I would stick it here to save people some grief because it is far from straight forward.

The issue is that complex queries are HORRIBLE to write using expression composition. It is far nicer to manually compose them with linq and collate using linqkit. The issue then becomes the ParameterExpression for your new predicate which is not the same as the one the ASPNet.Data library is using (info.DataItemExpression). The trick is to rebase your expression using the info.DataItemExpression. Not really that hard once you figure it out, but it took hours to figure it out :)

Code below for anyone interested. Hope this is useful

    using cpDataORM.Models;
    using cpDataServices.Models;
    using DevExtreme.AspNet.Data.Helpers;
    using LinqKit;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Linq.Expressions;

            CustomFilterCompilers.RegisterBinaryExpressionCompiler(info =>
            {
                if (info.DataItemExpression.Type == typeof(Approval))
                {
                    var queryableType = typeof(Queryable);
                    var whereMethod = queryableType.GetMethods()
                       .First(m =>
                       {
                           var parameters = m.GetParameters().ToList();
                           //Put more restriction here to ensure selecting the right overload                
                           //the first overload that has 2 parameters
                           return m.Name == "Where" && m.IsGenericMethodDefinition &&
                         parameters.Count == 2;
                       });
                    ParameterExpression pe = Expression.Parameter(typeof(Approval), "approval");
                    var genericMethod = whereMethod.MakeGenericMethod(typeof(Approval));
                    if (info.AccessorText == "EffectiveStatus" && info.Operation == "=")
                    {
                        var lstApprovalStatus = JsonConvert.DeserializeObject<List<ApprovalFilter.ApprovalStatusEnum>>(info.Value.ToString());
                        
                        List<Expression<Func<Approval, bool>>> lstStatusFilterExpression = new List<Expression<Func<Approval, bool>>>();

                        //Open approvals have no steps that approvesRequest that are statused approved or manually approved - or closed out
                        if (lstApprovalStatus.Contains(ApprovalFilter.ApprovalStatusEnum.Open)) lstStatusFilterExpression.Add(x => !x.ApprovalStep.Any(y => (((y.ApprovesRequest ?? false) &&
                            ((y.ApprovalStatus.IsApproval ?? false) || (y.ApprovalStatus.IsManual ?? false))) || (y.ApprovalStatus.IsCloseout ?? false))));
                        //Approved requests have a step that approvesRequest that are statused approved or manually approved
                        if (lstApprovalStatus.Contains(ApprovalFilter.ApprovalStatusEnum.Approved)) lstStatusFilterExpression.Add(x => x.ApprovalStep.Any(y => (y.ApprovesRequest ?? false) &&
                            (y.ApprovalStatus.IsApproval ?? false) || (y.ApprovalStatus.IsManual ?? false)));

    //code omitted for clarity

                        if (lstStatusFilterExpression.Count > 0)
                        {
                            ExpressionStarter<Approval> predicate = CompileWhereExpression(info, lstStatusFilterExpression);
                            return predicate.Body;
                        }
                        return null;
                    }
                }
                return null;
            });
        }

        private static ExpressionStarter<T> CompileWhereExpression<T>(IBinaryExpressionInfo info, List<Expression<Func<T, bool>>> lstStatusFilterExpression)
        {
            var predicate = PredicateBuilder.New<T>();
            foreach (Expression<Func<T, bool>> whereExpression in lstStatusFilterExpression)
            {
                var predicateRebase = new ParameterVisitor(whereExpression.Parameters, info.DataItemExpression as ParameterExpression)
                    .VisitAndConvert(whereExpression.Body, "or");
                predicate = predicate.Or(Expression.Lambda<Func<T, bool>>(predicateRebase, info.DataItemExpression as ParameterExpression));
            }

            return predicate;
        }

        class ParameterVisitor : System.Linq.Expressions.ExpressionVisitor
        {
            private readonly ReadOnlyCollection<ParameterExpression> from;
            private readonly ParameterExpression to;
            public ParameterVisitor(
                ReadOnlyCollection<ParameterExpression> from,
                ParameterExpression to)
            {
                if (from == null) throw new ArgumentNullException("from");
                if (to == null) throw new ArgumentNullException("to");
                this.from = from;
                this.to = to;
            }
            protected override Expression VisitParameter(ParameterExpression node)
            {
                for (int i = 0; i < from.Count; i++)
                {
                    if (node == from[i]) return to;
                }
                return node;
            }
        }
    }

**Comment by AlekseyMartynov** [comment]
Thank you for sharing your experience with us.
