### ISSUE TITLE
Filter Interceptor => ignoring a filter

### ISSUE THREAD

**Issue by statler** [DevExpress/DevExtreme.AspNet.Data#394]
When the client grid filters by client side calculated colu, it sends data like this;

[["Description","contains","open"],"or",[null,"=","open"]]

Obviously, this causes an exception in the datasourceloader.

I think the easiest way may be just to strip the null out on the server. Is there a way to use RegisterBinaryExpressionCompiler to ignore a filter property? It is easy enough if we just want to do it for the property null on a specific table because we know the type and can build an expression, but I want to do it on any table.

**Comment by AlekseyMartynov** [comment]
>  Is there a way to use RegisterBinaryExpressionCompiler to ignore a filter property?

Try this:

```c#
if(String.IsNullOrEmpty(info.AccessorText))
    return Expression.Constant(true);
```

**Comment by statler** [comment]
That works a treat. Thanks for your great work as always Aleksey.
