### ISSUE TITLE
Allow returning IQueryable without executing

### ISSUE THREAD

**Issue by sfrobous** [DevExpress/DevExtreme.AspNet.Data#395]
Method available in DataSourceLoader.LoadAsync works fine but it would be interesting if it was possible to get the IQueryable result of this, without actually executing it.

**Comment by AlekseyMartynov** [comment]
Use `Load` instead of `LoadAsync`. The query object itself is synchronous. Asynchrony begins when the query is executed:

```c#
var loadResult = DataSourceLoader.Load(_nwind.Orders, loadOptions);
var query = (IQueryable<Order>)loadResult.data;
var list = await EntityFrameworkQueryableExtensions.ToListAsync(query);
```

Note however that `LoadResult.data` is not always a query. Depending on the load options, it can be a `List<Group>` or an iterator.
