### ISSUE TITLE
Include js files to NuGet Package

### ISSUE THREAD

**Issue by TimHob** [DevExpress/DevExtreme.AspNet.Data#396]
I use the NuGet Package of this project and this package does not include the javascript files. Maybe it is possible to include these?

**Comment by AlekseyMartynov** [comment]
Hello

To install the JavaScript part, follow [this tutorial](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/docs/client-side-with-jquery.md).

While we technically could pack the script into the NuGet package, this would only work for MVC 5 projects but not for .NET Core projects. For this reason, NuGet includes .NET assemblies only.

See also:
- https://stackoverflow.com/a/52432770
- https://stackoverflow.com/a/55417737
- https://stackoverflow.com/a/43513137
- https://stackoverflow.com/a/48487588

**Comment by TimHob** [comment]
Hello Aleksey,
thank you for the quick answer and it makes totally sense tonot include the scripts to the NuGet package then. Sadly I am not able to use npm or unpkg due to our company guidlines. Right now we are working on a way to use npm packages, until then I will have to install and update the scripts manually.
