### ISSUE TITLE
Assistance with totalcount and groupcount when using ProjectTo

### ISSUE THREAD

**Issue by statler** [DevExpress/DevExtreme.AspNet.Data#410]
Hi Aleksey

Further to my work on #367, I have hit a bit of a snag. Everything works well enough, but I need some advice on some of the members of the LoadResult object.

In my strategy, I run the query on the base object and get the Ids returned by that query. I then run the query again on the projection with the filter being on the Ids from the first query. My issue is with what happens with totalcount, and possibly groupcount.

If I have say, a data set of 115 items and a page size of 20, then my first query will only return 20 ids. As a consequence, the totalcount in my second query will be 20 items. I can get around this easily enough by copying the totalcount from the first query.

What about the groupcount and summary items - and in the case of groups, the IEnumerable<group> in data. Are these going to cause me any issues?

Any ideas?

**Comment by AlekseyMartynov** [comment]
Hello

> I can get around this easily enough by copying the totalcount from the first query.

Correct.

> What about the groupcount and summary items - and in the case of groups, the IEnumerable in data. Are these going to cause me any issues?

Group keys and summary items should not cause any issue since `LoadResult` doesn't use their names.

Group data should not require any additional processing besides the transformation kindly described by you  in https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/338#issuecomment-573900547.
