### ISSUE TITLE
DataSourceLoader with raw sql

### ISSUE THREAD

**Issue by faikozgur** [DevExpress/DevExtreme.AspNet.Data#412]
We are using Devextreme components in a MVC project. Entity framework is employed in data access layer. In some part of the project we wanted to use raw sql queries and map the result to POCOs/DTOs.  We are passing SqlParameters to ctx.Database.SqlQuery<T> method and getting the result as IQueryable<T>. 
In webapi's action method Request.CreateResponse(DataSourceLoader.Load(_nwind.RawOrders, loadOptions)) throws and exception with message :"The SqlParameter is already contained by another SqlParameterCollection.".

I have modified the demo source code (Devexpress v19.1.5) to reproduce the issue. I have added the following code to InMemoryNorthwindContext file:
```csharp 
public IQueryable<Order> RawOrders  
        {  
            get  
            {  
                SqlParameter[] parms =  
                {  
                    new SqlParameter("@Freight", 1),  
                    new SqlParameter("@OrderDate", new DateTime(1900, 1,1 )),  
                };  
                return _nwind.Database.SqlQuery<Order>("SELECT * FROM Orders WHERE Freight> @Freight AND OrderDate > @OrderDate ", parms).AsQueryable();  
            }  
        }
```
and modified DataGridWebApiController file as follows (exception is thrown here):
```csharp
 public HttpResponseMessage Orders(DataSourceLoadOptions loadOptions) {  
            return Request.CreateResponse(DataSourceLoader.Load(_nwind.RawOrders, loadOptions));  
        }
```
I have also tested to add linq expressions after the raw sql query. The statements are executed without errors:
```csharp 
var exp = _nwind.RawOrders.Where(q => q.EmployeeID > 0).Skip(10).Take(20);  
var list = exp.ToList();
```
DevExtreme.AspNet.Data version is 2.4.3.

Edit: I have already opened a support ticket (T852831)

**Comment by AlekseyMartynov** [comment]
> Edit: I have already opened a support ticket (T852831)

DevExpress Support will review it shortly. I kindly ask you to avoid cross-posting tickets in the future.
