### ISSUE TITLE
CrossJoin - The LINQ expression could not be translated

### ISSUE THREAD

**Issue by crba233** [DevExpress/DevExtreme.AspNet.Data#413]
Hello!

**I'm getting this error:**

The LINQ expression could not be translated

**Here's the relevant libraries:**

EF Core 3.1
DevExtreme.AspNet.Data 2.5.1

**Here's an extremely simplified example:**

```
class Controller 
{
	private DbContext _dbContext;
	
	public async Task<LoadResult> Get(DataSourceLoadOptions loadOptions) {
		IQueryable<ParentDto> data =
			_dbContext.ATable
				.SelectMany(a =>
					_dbContext.BTable
						.Select(b => new
						{
							a.ATableID,
							a.ATableField,
							b.BTableID,
							b.BTableField
						})
				);
						
		return await DataSourceLoader.LoadAsync(data, loadOptions);
	}
}

class ATable
{
	public int ATableID { get; set; }
	public int ATableField { get; set; }
}

class BTable
{
	public int BTableID { get; set; }
	public int BTableField { get; set; }
}
```

**Here's my DataSourceLoadOptions:**

```
{
  "RequireTotalCount": true,
  "RequireGroupCount": false,
  "IsCountQuery": false,
  "Skip": 0,
  "Take": 100,
  "Sort": null,
  "Group": null,
  "Filter": [
    "ATableID",
    "=",
    237
  ],
  "TotalSummary": null,
  "GroupSummary": null,
  "Select": null,
  "PreSelect": null,
  "RemoteSelect": null,
  "RemoteGrouping": null,
  "PrimaryKey": null,
  "DefaultSort": null,
  "StringToLower": null,
  "PaginateViaPrimaryKey": null
}
```

**Here's what is happening:**

When the DataSourceLoader applies the filter it throws that exception, but when I do the filter manually (and without DataSourceLoadOptions::Filter set) it works just fine. This works just fine:

```
class Controller 
{
	private DbContext _dbContext;
	
	public async Task<LoadResult> Get(DataSourceLoadOptions loadOptions) {
		IQueryable<ParentDto> data =
			_dbContext.ATable
				.SelectMany(a =>
					_dbContext.BTable
						.Select(b => new
						{
							a.ATableID,
							a.ATableField,
							b.BTableID,
							b.BTableField
						})
				)
				.Where(x => 
					x.ATableID = 237
				);
						
		return await DataSourceLoader.LoadAsync(data, loadOptions);
	}
}

class ATable
{
	public int ATableID { get; set; }
	public int ATableField { get; set; }
}

class BTable
{
	public int BTableID { get; set; }
	public int BTableField { get; set; }
}
```

**Comment by AlekseyMartynov** [comment]
Hello

I cannot reproduce this. Here are my test cases based on your snippets:
- With an anonymous object: https://github.com/AlekseyMartynov/DevExtreme.AspNet.Data/commit/0d827297d821ec21fb2eb65bf3d4a6afd284e935
- With a DTO: https://github.com/AlekseyMartynov/DevExtreme.AspNet.Data/commit/081eefd38bf7d069b21d234ed763cd7dfdf2305a

Do you have a runnable project that I can debug?

**Comment by crba233** [comment]
I'll work on getting you that. In the meantime I switched the DevExtreme.AspNet.Data version over to v2.6.0-rc2 and am getting this error instead:
No generic method 'Where' on type 'System.Linq.Queryable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic.

**Comment by crba233** [comment]
Okay I finally figured it out!

```
IQueryable<object> data =
			_dbContext.ATable
				.SelectMany(a =>
					_dbContext.BTable
						.Select(b => new
						{
							a.ATableID,
							a.ATableField,
							b.BTableID,
							b.BTableField
						})
				);
```

It's because of the IQueryable<**object**>
Sorry, that's what the original example should have showed. That's what I get for doing copy pasta

**Comment by crba233** [comment]
Let me know if you still can't reproduce it and I'll give you the entire test project

**Comment by AlekseyMartynov** [comment]
`IQueryable<object>` erases element type information, and we treat it as `IQueryable<dynamic>`.

Try the following approach instead:
```c#
IQueryable data = ...;

await LoadNonGenericAsync(source, loadOptions);
```

```c#
public static Task<LoadResult> LoadNonGenericAsync(IQueryable source, DataSourceLoadOptionsBase options, CancellationToken cancellationToken = default(CancellationToken)) {
    var method = typeof(DataSourceLoader).GetMethod("LoadAsync").MakeGenericMethod(source.ElementType);
    return (Task<LoadResult>)method.Invoke(null, new object[] { source, options, cancellationToken });
}
```

**Comment by AlekseyMartynov** [comment]
> I switched the DevExtreme.AspNet.Data version over to v2.6.0-rc2 and am getting this error instead...

I'll check why the error has changed and whether we can throw a more helpful exception. Thanks for this info!

**Comment by crba233** [comment]
Thank you, I'll try out your solution.

**Comment by crba233** [comment]
Hello,

This worked wonderfully:

> `IQueryable<object>` erases element type information, and we treat it as `IQueryable<dynamic>`.
> 
> Try the following approach instead:
> 
> ```cs
> IQueryable data = ...;
> 
> await LoadNonGenericAsync(source, loadOptions);
> ```
> 
> ```cs
> public static Task<LoadResult> LoadNonGenericAsync(IQueryable source, DataSourceLoadOptionsBase options, CancellationToken cancellationToken = default(CancellationToken)) {
>     var method = typeof(DataSourceLoader).GetMethod("LoadAsync").MakeGenericMethod(source.ElementType);
>     return (Task<LoadResult>)method.Invoke(null, new object[] { source, options, cancellationToken });
> }
> ```
