### ISSUE TITLE
Support promise-like results for the onBeforeSend callback

### ISSUE THREAD

**Issue by artem-kurchenko** [DevExpress/DevExtreme.AspNet.Data#419]
[dx-sample.zip](https://github.com/DevExpress/DevExtreme.AspNet.Data/files/4434207/dx-sample.zip)
Currently `onBeforeSend` operates synchronously. It would be useful to make it asynchronous 
to support access token that may come from a web service.

```
let ds = createStore({  
    onBeforeSend: async (method, ajaxOptions) => {
          let token = await getAuthToken();
           ajaxOptions.headers = {
                   'Authorization': token
          };
     },
})
```

Related SC tickets:
[T875384](https://supportcenter.devexpress.com/ticket/details/t875384/aspnet-data-how-to-force-waiting-for-an-access-token-in-onbeforesend)

**Comment by AlekseyMartynov** [comment]
Related: #425
