### ISSUE TITLE
DataSourceLoader against Mongodb with BsonDocument/dynamic/ExpandoObject

### ISSUE THREAD

**Issue by pwen090** [DevExpress/DevExtreme.AspNet.Data#421]
Hello, we are trying to use DataSourceLoader (asp.net core app) against Mongodb using all dynamic data. E.g. We have do not have a C# Type or know of the model at compile time. So we are trying to work with for example ExpandoObject etc... 

We can use DataSourceLoader to load the DxGrid by returning a collection from Mongo as ExpandoObject. However filtering/sorting/etc do not work given there is no "real" Type for Linq (I assume) to work against.

Essentially how do we use asp.net core and DataSourceLoader to load dynamic data from Mongo and properly work with filter/sort/grouping of the grid? We are obviously open to using any dynamic/generic type e.g. could be BsonDocument - just that we only know about our model at run time and not compile time.

We can make this all "work" by converting to List<ExpandoObject> but we obviously do not want to do filtering/sorting/grouping in memory for the entire collection set.

**Comment by AlekseyMartynov** [comment]
Hello

It's not possible to be all-dynamic and LINQ-capable at the same time.

With the help of [`CustomAccessorCompilers`](https://devexpress.github.io/DevExtreme.AspNet.Data/net/api/DevExtreme.AspNet.Data.Helpers.CustomAccessorCompilers.html), `DataSourceLoader` can understand BSON document collections. However, you still need to specify property types manually:

```c#
// Add to Startup.Configure
DevExtreme.AspNet.Data.Helpers.CustomAccessorCompilers.Register((expr, accessorText) => {
    if(expr.Type == typeof(BsonDocument)) {
        var actualType = typeof(String); // TODO choose based on accessorText

        return Expression.Convert(
            Expression.Call(expr, "get_Item", new Type[0], Expression.Constant(accessorText)),
            actualType
        );
    }

    return null;
});
```

Test drive:
```c#
var client = new MongoClient("mongodb://localhost");
var source = client.GetDatabase("db1").GetCollection<BsonDocument>("collection1").AsQueryable();

var loadResult = DataSourceLoader.Load(source, new DataSourceLoadOptionsBase {
    Filter = new[] { "FirstName", "contains", "John" },
    RequireTotalCount = true
});
```

![](https://user-images.githubusercontent.com/4426185/79458959-4044f000-7ffb-11ea-9c2c-f12fe9a3591c.png)

**Comment by pwen090** [comment]
@AlekseyMartynov thank you, I will investigate that for Mongo. For now we were trying to do ExpandoObject and SQL JSON but it seems if we have IQueryable<ExpandoObject> that the Register customaccessor is not being called. Is there some special logic in Load/LoadAsync that makes it not call CustomAccessorCompilers for IQueryable<ExpandoObject>?

**Comment by AlekseyMartynov** [comment]
> For some reason the CustomAccessorCompilers code is not always called - does that only trigger if there is a filter?

`CustomAccessorCompilers` are used to read property values. Without any filter, sort, etc, `DataSourceLoader` doesn't call the associated code.

---

> the data comes back as a json array

The [`MongoDB.Integrations.JsonDotNet` package](https://www.nuget.org/packages/MongoDB.Integrations.JsonDotNet/) can help with this:

```c#
var doc = new BsonDocument {
    ["prop"] = 123
};

var json = JsonConvert.SerializeObject(doc, new JsonSerializerSettings {
    Converters = new[] {
        new MongoDB.Integrations.JsonDotNet.Converters.BsonDocumentConverter()
    }
});
// {"prop":123}
```

You can register `BsonDocumentConverter` globally in Startup.cs via [`JsonConvert.DefaultSettings`](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonConvert_DefaultSettings.htm) or `services.AddMvc().AddJsonOptions`.

I found this answer in https://stackoverflow.com/a/44216330. I suggest that you also use community resources, such as StackOverflow, for general MongoDB and JSON related questions.

**Comment by pwen090** [comment]
Sorry for the mistake about serialization. Just to note for others, we did fix that in a simplistic way via setting the mongo json writer to strict
`JsonWriterSettings.Defaults = new JsonWriterSettings { OutputMode = JsonOutputMode.Strict };`
and using their ToJson method to return the result:
```
result = DataSourceLoader.Load(source, loadOptions);
return Ok(result.ToJson());
```
We had an issue with sorting returning the error:
`Only fields are allowed in a $sort.`
We worked around that by a hack similar to this:
```
if(loadOptions.Sort!=null)
{
     var sorter = loadOptions.Sort[0].Selector;
     source = source.OrderBy(t => t[sorter]);
      loadOptions.Sort = null;
}
```
Not sure if there is a better way to fix sorting with CustomAccessorCompilers somehow?

Once we "fixed" sorting if we then in the grid did a group by a column, then expanded one of the groups, then sort on a different column we ended up with this error: 
`{"Compare(Convert({document}{OurGroupedColumn}, String), \"OurExpandedGroupedColumnValue\") is not supported."}
`
Is maybe a CustomAccessorCompilers workaround?

Thank you for the help and again sorry for the silly serialization mistake!

**Comment by AlekseyMartynov** [comment]
I'm glad to hear that you've found an alternative solution for the JSON serialization issue. Thanks for sharing.

Regarding the 'Only fields are allowed' exception, I checked it and found that Mongo provider doesn't support `Convert` expressions in `OrderBy`. This means that `CustomAccessorCompilers` should behave differently depending on the operation which is not currently possible. Fortunately, the workaround is quite simple.

> ...group by a column, then expanded one of the groups, then sort on a different column we ended up with this error

I guess this might be caused by the focused row feature (`focusedRowEnabled`). It can generate string comparison filters `string < "value"` filters that are not supported by Mongo provider. Please check if the error goes away with [`autoNavigateToFocusedRow`](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#autoNavigateToFocusedRow) set to `false`.

At this point, it seems to me that `BsonDocument` and `BsonValue` types require a special treatment in the library. I opened a ticket to track this: #422.

**Comment by pwen090** [comment]
@AlekseyMartynov tested with autoNavigateToFocusedRow set to false. It still ends up with the Compare(Convert error. I will close this Issue if there is nothing else you would like me to test. Thank you for opening 422 I will watch for updates!
