### ISSUE TITLE
Filtering on Enum fails in LoadAsync using Queryable

### ISSUE THREAD

**Issue by pwen090** [DevExpress/DevExtreme.AspNet.Data#429]
Is there a fix or workaround for doing filtering on Enum with a Queryable?

For example
`LoadResult result = await DataSourceLoader.LoadAsync(queryableSource, loadOptions);`

Where queryableSource is a class that one of the properties is an Enum and we are trying to filter on that Enum property/column. The code will result in an exception because of how DevExtreme is doing the translation it seems?

```
System.InvalidOperationException: The LINQ expression 'DbSet<Script>
    .Where(s => s.EnumType.ToString().Contains("test"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

Right now we use StringEnumConverter so when our asp.net core web api returns an Enum it returns a string to DevExtreme grid. This means that when the dxgrid filters the column it sends back loadOptions with the string and it seems LoadAsync does not know to convert the string back to the corresponding integer value of the enum to filter on.

We tried to work around this by instead storing our enum as string in SQL (instead of int). But it seems we get the same error as LoadAsync tries to still do the ToString().Contains for Enum instead of string compare that works with SQL/queryable.

It is not clear how do we setup an asp.net core web api to return enum and be filterable properly with DevExtreme using queryable instead of list?

**Comment by AlekseyMartynov** [comment]
Hello

This is an issue with EF Core 3. You can track it at https://github.com/dotnet/efcore/issues/20604.

If you need to support string operations, such as `Contains`, I suggest that you use the `String` type instead of an enum in your API.
