### ISSUE TITLE
Can't install devextreme-aspnet-data-nojquery

### ISSUE THREAD

**Issue by thenrich2009** [DevExpress/DevExtreme.AspNet.Data#431]
I get this error/warning when I 'npm install devextreme-aspnet-data-nojquery'
"npm WARN devextreme-aspnet-data-nojquery@2.6.1 requires a peer of devextreme@>=18.1.0 but none is installed. You must install peer dependencies yourself."

What peer package is it looking for specifically? There's no Nuget package called only devextreme.

**Comment by AlekseyMartynov** [comment]
Hello

This warning is about [npm peer dependencies](https://stackoverflow.com/q/26737819). It says that you need to install the `devextreme` npm package by running the following command:

```
npm install devextreme
```
