### ISSUE TITLE
DataSourceLoader.Load data with missing key properties

### ISSUE THREAD

**Issue by pwen090** [DevExpress/DevExtreme.AspNet.Data#434]
If you try to call DataSourceLoader.Load on an array of dynamic objects where some objects are missing keys then you will get an exception such as System.Collections.Generic.KeyNotFoundException: 'The specified key 'MissingProp' does not exist in the ExpandoObject.'

An example of the problem is shown below. Data will load fine in the datagrid but if you try to filter/group/sort on MissingProp column you will get the exception.
```
dynamic x1 = new ExpandoObject();
x1.BothProp = "test";
x1.MissingProp = "missing";
dynamic x2 = new ExpandoObject();
x2.BothProp = "test";

var test = new List<ExpandoObject> { x1, x2 };
LoadResult result = DataSourceLoader.Load(test, loadOptions);
```

Looking at the call stack the issue eventually ends up in System.Linq but is there a workaround or any ideas as it might relate to DevExtreme, RegisterBinaryExpressionCompiler or something? thank you

**Comment by AlekseyMartynov** [comment]
Hello

Would you please specify the exact load options and the stack trace?

When I try to sort or filter an array of ExpandoObjects with some properties uninitialized, I get a different exception:

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  Message='System.Dynamic.ExpandoObject' does not contain a definition for 'p'
```

A simple workaround is to initialize missing properties with `null` values.
