### ISSUE TITLE
Custom remote grouping aggregate functions

### ISSUE THREAD

**Issue by stowellt** [DevExpress/DevExtreme.AspNet.Data#435]
Hi,

Are there any plans to support remote grouping custom aggregate functions? This would allow support for user defined custom aggregate functions in the remote group expression compiler (see [EdmFunction](https://docs.microsoft.com/en-us/dotnet/api/system.data.metadata.edm.edmfunction?view=netframework-4.8))

**Comment by AlekseyMartynov** [comment]
Hello,

No, there are no such plans currently. Our implementation of remote grouping requires additional pre- and post-processing, even for the standard aggregate functions. In other words, a custom function would require additional supporting logic in the RemoteGroupExpressionCompiler code.

You can compute custom summaries in memory via [CustomAggregators](https://devexpress.github.io/DevExtreme.AspNet.Data/net/api/DevExtreme.AspNet.Data.Aggregation.CustomAggregators.html).

I would appreciate it if you tell us more about your use case and the context in which you refer to EdmFunction.
