### ISSUE TITLE
Add IBinaryExpressionInfo.StringToLower property

### ISSUE THREAD

**Issue by Franki1986** [DevExpress/DevExtreme.AspNet.Data#444]
Hi,

I have a custom expression for child lists. Now if it filters string properties I will lose the configuration for StringToLower, so that if I create my expression I can only create always StringToLower = true or false.

**Comment by AlekseyMartynov** [comment]
Hello,

While I understand the essence of your inquiry, it would also be helpful for me to understand the circumstances that cause you to need a dynamic `StringToLower`. Do you have an end-user option that can be changed at runtime?

**Comment by Franki1986** [comment]
I have different data-grids, where sometimes it is important to search a case insensitive text and sometimes you have to search for an exact case text. It is a feature our customers need.

**Comment by AlekseyMartynov** [comment]
> sometimes it is important to search a case insensitive text and sometimes you have to search for an exact case text

Does this apply to the same data member? In other words, isn't it possible to infer case sensitivity requirements from `IBinaryExpressionInfo.DataItemExpression`?

**Comment by Franki1986** [comment]
Do you have an example how to add these requirements  into the expression?
In my situation every devextreme datagrid component has the possibility to define if the string comparison is case sensitive or not.

**Comment by AlekseyMartynov** [comment]
> every devextreme datagrid component has the possibility to define if the string comparison is case sensitive or not.

Alright. Now I understand the requirements. Thank you.

I'll add `StringToLower` to [`IBinaryExpressionInfo`](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/2.7.0/net/DevExtreme.AspNet.Data/Helpers/IBinaryExpressionInfo.cs).
