### ISSUE TITLE
DataSourceLoadOptionsBase HttpPost Deserialize

### ISSUE THREAD

**Issue by excme** [DevExpress/DevExtreme.AspNet.Data#449]
Problem with deserialization api actions params in property Filter
For HttpGet:
![image](https://user-images.githubusercontent.com/13168074/95197675-a0fef980-07e2-11eb-9db9-d6e1e909e171.png)

For HttpPost
![image](https://user-images.githubusercontent.com/13168074/95198410-df48e880-07e3-11eb-8863-352bbff97be4.png)
It`s reason, why DataSourceLoader can use Filter
![image](https://user-images.githubusercontent.com/13168074/95198567-1c14df80-07e4-11eb-9240-b34bd480c413.png)

Asp.Net Core 3.1
System.Text.Json 4.7.2

`
services.AddJsonOptions(conf =>
{
   conf.JsonSerializerOptions.PropertyNamingPolicy = null;
})
`

**Comment by AlekseyMartynov** [comment]
Hello

I see that you are using custom serialization and deserialization routines for the load options.
Would you please share the code so I can debug it and hopefully help?

You can also check the default code that we suggest to use in ASP.NET projects:
- https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/2.7.1/net/Sample/DataSourceLoadOptions.cs#L22
- https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/2.7.1/net/DevExtreme.AspNet.Data/Helpers/DataSourceLoadOptionsParser.cs

**Comment by excme** [comment]
I am creating a custom JsonConverter for System.Json.Text. I partial solution, but already it`s fix error on "Filter" property
```
public class JsonCustomConverter : JsonConverter<DevExtreme.AspNet.Data.DataSourceLoadOptionsBase>
    {
        public override DataSourceLoadOptionsBase Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                throw new JsonException();
            }
            var dbOptions = new DataSourceLoadOptionsBase();
            while (reader.Read())
            {
                if (reader.TokenType == JsonTokenType.EndObject)
                {
                    return dbOptions;
                }

                if (reader.TokenType == JsonTokenType.PropertyName)
                {
                    string propertyName = reader.GetString();
                    reader.Read();
                    switch (propertyName)
                    {
                        case "Take":
                            dbOptions.Take = reader.GetInt32();
                            break;

                        case "Skip":
                            dbOptions.Skip = reader.GetInt32();
                            break;

                        case "RequireTotalCount":
                            dbOptions.RequireTotalCount = reader.GetBoolean();
                            break;

                        case "Filter":
                            dbOptions.Filter = new List<object>(); 
                            do
                            {
                                reader.Read();
                                switch (reader.TokenType)
                                {
                                    case JsonTokenType.String:
                                        dbOptions.Filter.Add(reader.GetString());
                                        break;
                                    case JsonTokenType.Number:
                                        dbOptions.Filter.Add(reader.GetDouble());
                                        break;
                                }
                            } while (reader.TokenType != JsonTokenType.EndArray);

                            break;
                    }
                }

            }

            throw new JsonException();
        }

        public override void Write(Utf8JsonWriter writer, DataSourceLoadOptionsBase value, JsonSerializerOptions options)
        {
            throw new NotImplementedException();
        }
    }
```

**Comment by AlekseyMartynov** [comment]
In general, filter expressions can contain deeply nested arrays. For example, `[ [ "a", 1 ], "and", [ "b", 2 ] ]`. Make sure to consider this in your custom converter.

**Comment by excme** [comment]
> In general, filter expressions can contain deeply nested arrays. For example, `[ [ "a", 1 ], "and", [ "b", 2 ] ]`. Make sure to consider this in your custom converter.

Yes, I found now. I am searching solution for filter now. Maybe you know a Converter in System.Text.Json ?

**Comment by AlekseyMartynov** [comment]
> Maybe you know a Converter in System.Text.Json ?

No, I don't. I suggest that you take our built-in [client-side serialization](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/2.7.1/js/dx.aspnet.data.js#L127-L176) and [server-side deserialization](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/2.7.1/net/DevExtreme.AspNet.Data/Helpers/DataSourceLoadOptionsParser.cs) routines as a basis for your code.
