### ISSUE TITLE
Support LINQKit query provider

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#451]
https://github.com/scottksmith95/LINQKit
Requested in https://devexpress.com/issue=T938176

**Comment by statler** [comment]
Hi Aleksey

How is this one travelling? I too have need of this functionality.

**Comment by AlekseyMartynov** [comment]
Hello @statler 

I checked this quickly today: https://github.com/AlekseyMartynov/DevExtreme.AspNet.Data/commit/56b46b547c978be29bed49a649c53d2d1e1a414b
I'd appreciate if you try this changeset (1 file) and let me know how it works for you.

**Comment by statler** [comment]
Sorry @AlekseyMartynov - only just saw this. Will try to look tomorrow

**Comment by statler** [comment]
@AlekseyMartynov - I got back to this finally. Is this in the package or do I need to clone and run locally?

**Comment by AlekseyMartynov** [comment]
Great!
No, this changeset has not yet been merged.

**Comment by statler** [comment]
@AlekseyMartynov - this worked for my use case. Can you let me know when merged please.

**Comment by AlekseyMartynov** [comment]
Released in [2.8.3](https://github.com/DevExpress/DevExtreme.AspNet.Data/releases/tag/2.8.3)

**Comment by statler** [comment]
Thank you Aleksey. Very much appreciated - sorry it took so long to review.
