### ISSUE TITLE
RemoteGroupExpressionCompiler converts 

### ISSUE THREAD

**Issue by Patrick-Spiegel** [DevExpress/DevExtreme.AspNet.Data#458]
I have an issue with the `RemoteGroupExpressionCompiler`. 
![image](https://user-images.githubusercontent.com/35311793/97859183-8a27c600-1d00-11eb-8514-3b37358ca697.png)
Here the expression compiler tries to call the `DynamicSum.Calculate` method which fails with an exception (no overload found with this type parameters).

I have updated my `CustomAccessorCompiler` to Generate an `Expression` with type `Expression<Func<T, object>>`.

![image](https://user-images.githubusercontent.com/35311793/97859084-606e9f00-1d00-11eb-84ac-cbb9b9a8ab20.png)

 This fixed the error but this now led to another error I cannot fix. 

![image](https://user-images.githubusercontent.com/35311793/97859955-9bbd9d80-1d01-11eb-8600-2edfaf5024be.png)

![image](https://user-images.githubusercontent.com/35311793/97859939-96605300-1d01-11eb-9d33-1daa906fae01.png)

What can I do to fix this?

**Comment by AlekseyMartynov** [comment]
Hello

First, would you please clarify why you are using `RemoteGrouping` with expando objects? `RemoteGrouping` is only useful when the source collection is a LINQ query. 

Actually, I added `DynamicSum` for a [particular support case](https://devexpress.com/issue=T598818), and that customer reported that it worked well for their needs.

**Comment by Patrick-Spiegel** [comment]
Hello,

I was able to break down the issue to the fact that we are implementing `IDynamicMetaObjectProvider`. I will look if we can get rid of it on our side or if we need more changes made.

**Comment by Patrick-Spiegel** [comment]
Can confirm that IDynamicMetaObjectProvider caused issues. No more work is needed.
