### ISSUE TITLE
Search/filter by calculated field

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme.AspNet.Data#459]
Hi, I'm using EF/SQL Server and have a calculated property, but search/filtering is not working out of the box because DataSourceLoader cannot convert expression to linq.

Example of our calculated property: we have a Product with a price history, we need to display last price, calculated property is similar to this:

```
public string LastPrice { 
get {
  if(History!=null && History.Count > 0) {
     var lastPrice = History.OrderByDescending(_=>_.Date).First();
     return lastPrice.Price + "(" + lastPrice.Date.ToString("dd.MM.yyyy") + ")";
  }
  return null;
 }
}
```
where Histroy type is `ICollection`

@AlekseyMartynov, sorry, it's an EF issue: calculated field in where clause cannot be translated because there is no such field in a database.
So, I don't need to use calculated properties and can construct cell value via `calculateCellValue` on frontend. I need to use RegisterBinaryExpressionCompiler to construct same text as in frontend and search on it, but it's not easy to create such expression tree and I'm not good in expression trees... Can you please help me to constrcuct it?

**Comment by Bykiev** [comment]
Finally, I was able to construct needed expression tree:
1. Call OrderByDescending
2. Call Select (with date formatting using DbFunctions
3. Call FirstOrDefault
3. Call Contains

**Comment by AlekseyMartynov** [comment]
Cool.
Thanks for letting us know about another success with custom compilers 😄

**Comment by Bykiev** [comment]
It's really very powerful, but requires some skills!
