### ISSUE TITLE
How can we handle null object return in dataSource: DevExpress.data.AspNet.createStore for loadurl?

### ISSUE THREAD

**Issue by RachanaPA** [DevExpress/DevExtreme.AspNet.Data#460]
How can we handle null object return in dataSource: DevExpress.data.AspNet.createStore for loadurl?

**Comment by AlekseyMartynov** [comment]
I need more details to help you with this question. Please describe steps to reproduce, or share a sample project to illustrate the behavior that you need to solve.

**Comment by RachanaPA** [comment]
I could resolve . added below code in  processLoadResponse function. Thank you :)
 if (res === null) 
            res = [];

function processLoadResponse(d, res, getResolveArgs) {

        res = expandLoadResponse(res);
        if (res === null) // added to check null object return
            res = [];


        if(!res || typeof res !== "object")

            d.reject(new Error("Unexpected response received"));

        else

            d.resolve.apply(d, getResolveArgs(res));

    }
