### ISSUE TITLE
Provide an option on the behaviour for DateTime conversion of filters to support UTC

### ISSUE THREAD

**Issue by statler** [DevExpress/DevExtreme.AspNet.Data#462]
Further to https://supportcenter.devexpress.com/ticket/details/t946006/parameterization-of-queries-in-devextreme-aspnet-data

The current filter behaviour is problematic with servers with different timezone configurations to the database. For example, a machine in UTC+11 and a database where dates are stored in UTC. The current behaviour means the following does not give the expected result

["DateRaised",">=","2017-10-02T03:49:42-03:00"]

The DateTime conversion

https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/e7cc8305fa5e8d0fc202ab94553c4a81a1ebb37e/net/DevExtreme.AspNet.Data/Utils.cs#L48

automatically converts it into _local_ DateTime. We need the query to always run as UTC, as that is the common reference for our database. 

At the moment, using the above as a query results in the following, and I don't know how it could be scaleable changed with the existing codebase:

2017-10-02T03:49:42 adjusted 3 hours to UTC => 2017-10-02T06:49:42
2017-10-02T06:49:42 adjusted 11 hours to local time => 2017-10-02T17:49:42

**Comment by AlekseyMartynov** [comment]
Hello

My fellow support engineer Lex prepared an in-depth answer to the mentioned ticket:
https://supportcenter.devexpress.com/ticket/details/t946006#33416bfa-2954-4351-ab7f-c5f3abd37920
