### ISSUE TITLE
Filtering against fields from DynamicObject derived classes with MongoDb

### ISSUE THREAD

**Issue by matthew-dexter-trimble** [DevExpress/DevExtreme.AspNet.Data#464]
I am trying to write a CustomAccessorCompiler which works with a field from a System.Dynamic.DynamicObject derived class and I can't seem to find the right syntax.

The class is strongly typed for some fields but dynamically typed for others since we need a flexible representation in the database - internally the dynamic fields are managed in a Dictionary<string,object>. There is nothing special about the implementation - it is very similar to this one - https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject?view=netcore-3.1

Ultimately I am trying to use this against an IQueryable returned from a collection in MongoDb and I am targeting .NET Core 3.1

Following the example in #421 which creates an expression to call against a BsonDocument using the get_Item method on BsonDocument, I've been trying to figure out the Expression I need without a lot of success. 

Things I've tried so far:

Adding a get_Item method into my DynamicData derived class to mimic the method in the BsonDocument but all I get is a message that the method is not supported - I'm not sure if the get_Item here is the underlying method for the get part of a property or something else.

I've also tried PropertyExpression but that requires a strongly typed property on the object - this works great for the strongly typed properties but not for the dynamic ones.

I've also tried using a LambdaExpression to return a PropertyExpression but I confess the syntax is just a bit too cryptic for me and I've had little success.

Anyway at this point I'm pretty stumped - I feel sure this is possible because at the end of the day the MongoDb driver works with LINQ expressions so all I need to do is find the right expression and I'll be in business.

So any help would be very gratefully received.

**Comment by AlekseyMartynov** [comment]
Hello

[This StackOverflow thread](https://stackoverflow.com/a/3591820) explains how you can build dynamic expression trees in code. However, I don't think that the MongoDB LINQ provider can handle them.

**Comment by matthew-dexter-trimble** [comment]
Thanks for this it is useful but in this case I am not using the dynamic keyword just creating classes derived from DynamicObject much like an expando object - not sure if that makes a difference here.

I stepped through the code in the library and found the following snippet for supporting expando objects which I tried using in a CustomAccessorCompiler

```
 static Expression ReadExpando(Expression expando, string member) {
            return Expression.Property(
                Expression.Convert(expando, typeof(IDictionary<string, object>)),
                "Item",
                Expression.Constant(member)
            );
        }
```

I made my DynamicObject class implement IDictionary delegating to the internal dictionary object which holds the dynamic key/value pairs.

At this point I'm getting the following error in my example code

```
System.InvalidOperationException
  HResult=0x80131509
  Message=DynamicCompare({document}.Item["Name"], "Harry", False) is not supported.
  Source=MongoDB.Driver
  StackTrace:
   at MongoDB.Driver.Linq.Translators.PredicateTranslator.GetFieldExpression(Expression expression)
```
So it seems as if the DynamicCompare function wouldn't be supported by MongoDb - is there a way of substituting a different expression for this or maybe even native MongoDb code - MongoDb seems to support injecting filters into a LINQ statement which support untyped fields - 

https://mongodb.github.io/mongo-csharp-driver/2.3/apidocs/html/M_MongoDB_Driver_Linq_LinqExtensions_Inject__1.htm

and

https://stackoverflow.com/questions/61851443/filtering-using-asqueryable-in-mongodb-c-sharp-expandoobject#answer-61959703:~:text=Update%20(you%20can%20have%20multiple%20conditions%2C%20and%20different%20kinds%20of%20null%20checking)

Any way of implementing something like this - I notice you can have a CustomFilterCompiler as well as a CustomAccessorCompiler - could I use something like this do you think?

**Comment by matthew-dexter-trimble** [comment]
Also stumbled upon this - https://github.com/axelheer/nein-linq, do you think something like this might be workable?

**Comment by AlekseyMartynov** [comment]
The `ReadExpando` and `DynamicCompare` functions, that you have mentioned, are there for in-memory operations on dynamic data, such as lists of expando objects. LINQ providers cannot translate these expressions.

It is correct that MongoDB LINQ provider can execute queries on untyped collections.

```c#
var client = new MongoClient("mongodb://localhost");
var source = client.GetDatabase("test").GetCollection<BsonDocument>("test").AsQueryable();
```

### 1. With explicit conversion to a concrete type (discussed in #421):
```c#
var query = source
    .Where(i => (int)i["prop1"] > 123)
    .OrderBy(i => i["prop1"]);
```
represented internally as 
```c#
.Where(i => (Convert(i.get_Item("prop1"), Int32) > 123))
.OrderBy(i => i.get_Item("prop1"))
```
This can possibly work if we add more context to the `CustomAccessorCompilers.Register` callback. Additional context will help distinguish filters that require type conversion from sorting that doesn't accept type conversion.

However, the fact that each custom accessor requires a specific type devalues the 'untyped intent' of the approach.

### 2. With implicit conversion to `BsonValue` (researched in #422):
```c#
var query = source
    .Where(i => i["prop1"] > 123)
    .OrderBy(i => i["prop1"]);
```
represented internally as
```c#
.Where(i => (i.get_Item("prop1") > Convert(123, BsonValue)))
.OrderBy(i => i.get_Item("prop1"))
```
This approach has fundamental limitations, as I wrote in https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/422#issuecomment-683923866. `DataSourceLoader` needs member type information to make important decisions when it builds internal expression trees.

We don't plan to add support for untyped MongoDB collections at this time.

**Comment by matthew-dexter-trimble** [comment]
OK - so essentially are you saying there is no way of achieving what I'm trying to do? It sounds like the first option isn't useable without typing the accessor (pardon my ignorance but is there no way of doing this using generics?)

And the second option is not supported and you have no plans to enable this scenario.

Do you have any suggestions for any alternative approaches I could take?

**Comment by matthew-dexter-trimble** [comment]
OK thanks, I'll investigate the feasibility of these approaches and close this issue.

I would like to request that you consider making using untyped or partially typed this kind of thing easier however as it does reduce the usability of this library for MongoDb without it.

Thanks for your help.
