### ISSUE TITLE
CustomAccessorCompilers is working wrong on excel export with grouping

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme.AspNet.Data#466]
@AlekseyMartynov, hello!

I'm using `CustomAccessorCompilers` with DbFunctions, but when export to excel is applied with grouping on such column it seems to be evaluated on `IEnumberable` instead of `IQuerable` and I'm getting an error that DbFunctions can be only invoked from LINQ to Entities. Also now I understand why it takes so much time to export filtered dataGrid. Is any workaround for this?

Part of the stack trace:
```
"Message":"An error has occurred.",
"ExceptionMessage":"This function can only be invoked from LINQ to Entities.",
"ExceptionType":"System.NotSupportedException","StackTrace":"   
в System.Data.Entity.DbFunctions.Right(String stringArgument, Nullable`1 length)\r\n  
 в lambda_method(Closure , CustomModel2)\r\n   
 в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n  
 в System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)\r\n  
 в lambda_method(Closure , CustomModel)\r\n   
 в DevExtreme.AspNet.Data.Helpers.DefaultAccessor`1.Read(T obj, String selector)\r\n 
 в DevExtreme.AspNet.Data.GroupHelper`1.GetKey(T obj, GroupingInfo groupInfo)\r\n  
 в DevExtreme.AspNet.Data.GroupHelper`1.Group(IEnumerable`1 data, GroupingInfo groupInfo)\r\n  
 в DevExtreme.AspNet.Data.GroupHelper`1.Group(IEnumerable`1 data, IEnumerable`1 groupInfo)\r\n   
 в DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.<ContinueWithGroupingAsync>d__7`1.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n  
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n 
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n 
 в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n 
 в DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.<LoadAsync>d__5.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n 
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
 в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n  
```

**Comment by AlekseyMartynov** [comment]
Hello

Export implies that all groups are expanded and all data rows are visible. In these circumstances, `DataSourceLoader` only uses the underlying LINQ provider to sort and filter data, while grouping is done in memory.

The stack trace indicates that the error occurs while evaluating a group key. If you can detect that the request is initiated by the Data Grid exporter, then you should be able to modify `loadOptions.Group` to not use custom accessors that require `DbFunctions`.

**Comment by Bykiev** [comment]
@AlekseyMartynov, thank you!

I was able to detect exporting to excel in `onExporting` event and then remove group in `onBeforeSend` event, but if there is a lot of data `OutOfMemoryExceptions` occures. I have 16 GB of RAM, is any workaround for this issue?
