### ISSUE TITLE
Q: Load Options for json

### ISSUE THREAD

**Issue by leonkosak** [DevExpress/DevExtreme.AspNet.Data#470]
My use case

Is somehow possible to apply LoadOptions object to json object in SQL column?

There is jsonb data type for Postgres and this jsonb object can be used in LINQ queries: https://www.npgsql.org/efcore/mapping/json.html
query example: https://www.npgsql.org/efcore/mapping/json.html#querying-json-columns

I am wondering if is possible to "directly" apply LoadOptions object to jsonb column in some SQL table?
Thank you.

**Comment by AlekseyMartynov** [comment]
Hello,

Internally, `DataSourceLoader` translates load options into one or more LINQ expressions. If you can express your requirement in LINQ terms, such as `.Where().OrderBy().Select()`, `DataSourceLoader` can possibly handle it too.

**Comment by leonkosak** [comment]
Thank you.
So basically, LINQKit ([DX issue on GH](https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/451)) would be nice and elegant solution, but currently I have to manually "parse" LoadOptions on backend and manually translate to LINQ terms (.Where().OrderBy()...)?

**Comment by AlekseyMartynov** [comment]
Please clarify whether or not you have an unresolved issue that I can help you with. If so, then describe how I can reproduce it on my side. A simple runnable project would be great.

**Comment by leonkosak** [comment]
Currently, I have no minimal VS solution, just full application.

`DataSourceLoader.Load(_repository.Select(x => x.MyJsonbPropertyColumn), loadOptions);`

So basically, this should work, right?

**Comment by AlekseyMartynov** [comment]
This code may or may not work depending on many factors, such as actual load options, JSON mapping details, and PostgreSQL LINQ provider capabilities. 

If it fails in your app, please capture the exception and post it here, including the complete stack trace. This will be a good starting point.

**Comment by leonkosak** [comment]
@AlekseyMartynov, we try:

`DataSourceLoader.Load(_repository.Select(x => x.MyJsonbPropertyColumn), loadOptions);`

and it works! :)
There is identical Json structure (based on C# class) in `MyJsonbPropertyColumn` jsonb column.
