### ISSUE TITLE
Decrypt DataSourceLoadOptions on data requests

### ISSUE THREAD

**Issue by Alexander-Leontiev** [DevExpress/DevExtreme.AspNet.Data#475]
All the entity IDs are considered as security-sensitive data at my project. We encrypt them before being passed to client-side and decrypt them when handling requests.
Now we are on the way of migration our data grids to DevExtreme. Our security standards must be applied to grids' client-server interaction. Currently I see no other way to achieve that but to have the following server pipeline:
- write a routine to pass through recieved DataSourceLoadOptions;
- decrypt all encrypted data and write decrypted values back to DataSourceLoadOptions;
- pass modified DataSourceLoadOptions to DataSourceLoader.

Is there any more convenient way to do what I need?

**Comment by AlekseyMartynov** [comment]
Hello,
Please check DevExpress Support reply at https://devexpress.com/issue=T987990
