### ISSUE TITLE
Json Filter on DateTimeOffset field is returning 0 rows

### ISSUE THREAD

**Issue by vsimonaitis** [DevExpress/DevExtreme.AspNet.Data#477]
When filtering is applied on DateTimeOffset column and target value is passed as a string, filtering works fine.

But when filter is deserialized from Json object (JSON used for WebApi request) NewtonSoft automatically Deserializes dates into DateTime. When DateTime filter is applied on DateTimeOffset, it produces a SQL where condition "@p2=1" where p2 equals 0. In other words it returns 0 rows no matter what. 
```
var proj = new TestData();
                proj.date = DateTime.UtcNow;
                proj.timestamp = DateTimeOffset.UtcNow;
                proj.categoryTitle = "P1";
                session.Save(proj);
                {
                    var loadOptions = new SampleLoadOptions
                    {
                        Filter = new[] { "timestamp", ">", "2020-01-01T18:04:57.610Z" },
                        RequireTotalCount = true
                    };
                    var loadResult = DataSourceLoader.Load(session.Query<TestData>(), loadOptions);

                    Assert.GreaterOrEqual(loadResult.totalCount, 1); // Success
                }
                {
                    var source = new[] { new TestData() { timestamp = DateTimeOffset.UtcNow } };

                    var filter = JsonConvert.DeserializeObject<IList>(@"[ ""timestamp"", "">="", ""2020-03-03T18:04:57.610Z"" ]");

                    var loadOptions = new SampleLoadOptions
                    {
                        Filter = filter,
                        RequireTotalCount = true
                    };

                    var loadResult = DataSourceLoader.Load(source, loadOptions);
                    Assert.GreaterOrEqual(loadResult.totalCount, 1); // Fail
                }
```
PS: I would prefer to get an exception instead of 0 results.

**Comment by AlekseyMartynov** [comment]
Thanks for reporting. We will fix this case of `DateTime` to `DateTimeOffset` conversion. As a workaround, you can use`DateParseHandling = None`, refer to https://github.com/JamesNK/Newtonsoft.Json/issues/862

> PS: I would prefer to get an exception instead of 0 results.

I agree with you, that this complicates debugging. However, we prefer to mute errors when, for instance, an end user enters text into a numeric column filter.

**Comment by vsimonaitis** [comment]
Just a suggestion: Maybe the library could output error in the _resultObject_ in a separate _error_ property? It would not affect _DataGrid_ behavior but would be very useful for developers.

**Comment by AlekseyMartynov** [comment]
Thanks for the idea. I opened an individual ticket #479 to track it.
