### ISSUE TITLE
A problem with DevExtreme 21.1.2-beta

### ISSUE THREAD

**Issue by jzs11** [DevExpress/DevExtreme.AspNet.Data#485]
Hi team,
I tried to use this within a Vue3 component and it turns out the following error. The component works well with DevExtreme 20.2.

![image](https://user-images.githubusercontent.com/2770401/118726813-f37abb00-b885-11eb-9ccc-bf3431d11ca0.png)

Following the documentation - https://js.devexpress.com/Documentation/21_1/Guide/Data_Binding/Specify_a_Data_Source/Web_API,_PHP,_MongoDB/

It gives the error

![image](https://user-images.githubusercontent.com/2770401/118727055-4e141700-b886-11eb-8099-dea454242eca.png)

**Comment by AlekseyMartynov** [comment]
Thank you for testing DevExtreme beta.
We are working an a fix.

**Comment by AlekseyMartynov** [comment]
Would you please check a fixed package?
https://www.npmjs.com/package/devextreme-aspnet-data-nojquery/v/2.8.4

**Comment by jzs11** [comment]
Looking good! Thanks for the fix. 👍 (By the way, it would be awesome to use System.Text.Json instead of Json.Net to use the build in JSON support in .net core). 
Thanks again!

**Comment by AlekseyMartynov** [comment]
Thank you.

Regarding JSON serializer. In 2.x we'll stick to Newtonsoft for compatibility with existing projects and products. Later on, when/if we drop support for older frameworks, we may switch to System.Text.Json.
