### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by mskutlu** [DevExpress/DevExtreme.AspNet.Data#488]
Currently this library depends on .net 4.5 and .net 2.0 and it is not working on linux. Maybe in future, it could upgrade to .net core.

**Comment by AlekseyMartynov** [comment]
Hello

> .net 2.0

Actually, it is [.NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) which means compatibility with .NET Core 2.0 onward.

If you have a Linux-specific issue, please describe it in a greater detail, and we'll try to help.

**Comment by mskutlu** [comment]
thank you for information. After your comment, i tried again with latest version and it is running without problem.
