### ISSUE TITLE
Allow to modify loadParams at any time

### ISSUE THREAD

**Issue by alfeg** [DevExpress/DevExtreme.AspNet.Data#490]
We have an additional fields that can be changed during page lifecycle.

Right now we recreate store every time params changed, but it would be much better to just tell store that load params have changed.

**Comment by AlekseyMartynov** [comment]
Hello,

I think you can achieve this by handling `onBeforeSend` ([docs](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/docs/client-side-with-jquery.md#configuration)). It allows to intercept and customize AJAX requests, including their HTTP method, url, headers and request body.
