### ISSUE TITLE
Avoid lifting to nullable

### ISSUE THREAD

**Issue by sgtHoloToaster** [DevExpress/DevExtreme.AspNet.Data#493]
Hello! I have a problem with filtering grid by a nested non-nullable property. My code looks like this:

```
public class ChildModel
{
    public DayOfWeek EnumProp { get; set }
}

public class ParentModel
{
    public ChildModel Child { get; set; }
}
```

`Child` is always not null, but when I try to filter by condition like `Child.EnumProp", "=", 1`, I get my value lifted to `Nullable<DayOfWeek>`, resulting in an exception thrown by EF Core: `System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.Nullable`1[System.DayOfWeek]' and 'System.DayOfWeek'.`

I assume that it's related to changes made when fixing #240 

Is there a way to avoid lifting to nullable in this case? Or maybe you know a workaround how the necessary conversion can be made on the Entity Framework Core side?

Thanks in advance!

**Comment by AlekseyMartynov** [comment]
Hello

Please check this test:
https://github.com/AlekseyMartynov/DevExtreme.AspNet.Data/blob/issue-493/net/DevExtreme.AspNet.Data.Tests.EFCore/Bug493.cs

The filter runs successfully.

Expression:
```c#
[Microsoft.EntityFrameworkCore.Query.QueryRootExpression].Where(obj => (obj.Child.EnumProp == Monday))
```

SQL:
```sql
SELECT [b].[ID], [b].[ParentID]
FROM [Bug493_ParentModel] AS [b]
LEFT JOIN [Bug493_ChildModel] AS [b0] ON [b].[ParentID] = [b0].[ID]
WHERE [b0].[EnumProp] = 1
```
Have I missed any important detail?

**Comment by sgtHoloToaster** [comment]
Thank you for your answer! I played around with this test case and it turned out that I missed some important detail. Even though the Child cannot be null we had a not-so-implicit mapping with a null-check. With that, the test you provided will look like this:
```
public class Bug493 {

    [Table(nameof(Bug493) + "_" + nameof(ParentModel))]
    public class ParentModel {
        public int ID { get; set; }

        [ForeignKey(nameof(ChildModel.ParentID))]
        public ChildModel Child { get; set; }
    }

    [Table(nameof(Bug493) + "_" + nameof(ChildModel))]
    public class ChildModel {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public DayOfWeek EnumProp { get; set; }
    }

    [Table(nameof(Bug493) + "_" + nameof(ParentDto))]
    public class ParentDto {
        public ChildDto Child { get; set; }
    }

    [Table(nameof(Bug493) + "_" + nameof(ChildDto))]
    public class ChildDto {
        public DayOfWeek EnumProp { get; set; }
    }

    [Fact]
    public async Task Scenario() {
        await TestDbContext.ExecAsync(context => {
            var parents = context.Set<ParentModel>();

            parents.Add(new ParentModel {
                Child = new ChildModel {
                    EnumProp = DayOfWeek.Monday
                }
            });

            context.SaveChanges();
            var query = parents.Select(p => new ParentDto {
                Child = p.Child == null ? null : new ChildDto {
                    EnumProp = p.Child.EnumProp
                }
            });

            var loadResult = DataSourceLoader.Load(query, new SampleLoadOptions {
                Filter = new object[] { "Child.EnumProp", 1 },
            });

            Assert.NotEmpty(loadResult.data);
        });
    }
}
```

Notice the null check `p.Child == null ? null : new ChildDto`. Turned out that this is the cause of the issue. In cases like this, Linq.Expression converts all the ChildDto value type props to nullable types. And it looks like this is not something you can detect when compiling a query

And in the case you may be curious I also played around with this scenario and found some additional details:
if we write a query like this
```
var monday = DayOfWeek.Monday;
var query = parents.Select(p => new ParentDto {
    Child = p.Child == null ? null : new ChildDto {
        EnumProp = p.Child.EnumProp
    }
}).Where(p => p.Child.EnumProp == monday);
```

using just Linq.Expressions, it results in

```
DbSet<ParentModel>()
    .Select(p => new ParentDto{ Child = p.Child == null ? null : new ChildDto{ EnumProp = p.Child.EnumProp }
         }
    )
    .Where(p => (int)p.Child.EnumProp == (int)<>c__DisplayClass4_0.monday)
```

Notice the conversion to `int`. The DevExpress query builder doesn't do that, it leaves the parameters as enums. And this way there's no problems with filtering. But nevertheless, now it fails to map results to ChildDto, because of EnumProp returning type is still nullable while the type is in the model is not: 
```
System.InvalidOperationException : Rewriting child expression from type 'System.DayOfWeek' to type 'System.Nullable`1[System.DayOfWeek]' is not allowed, because it would change the meaning of the operation. If this is intentional, override 'VisitUnary' and change it to allow this rewrite.
```

And even if we rewrite the `Where` clause to `Where(p => p.Child != null && p.Child == monday)` it still won't help avoiding the lifting to nullable. So I am not sure if this can be solved on your side

As for us, we decided to just remove this null check and now it works fine. But I'm also thinking about asking CoreLib maintainers to advice about this kind of situation, because I'm sure that in the future we will face it again

Thanks for your time! 

And of course feel free to close the issue if you don't have any additional ideas

**Comment by AlekseyMartynov** [comment]
Thanks for the additional research.

> Notice the conversion to int. The DevExtreme query builder doesn't do that, it leaves the parameters as enums.

You can actually see this difference with plain C# too. Please compare:

```c#
Expression<Func<ParentDto, bool>> where1 = i => i.Child.EnumProp == DayOfWeek.Monday;

// (System.Int32)($i.Child).EnumProp == 1
```

vs.

```c#
var p2 = Expression.Parameter(typeof(ParentDto), "i");
Expression<Func<ParentDto, bool>> where2 = Expression.Lambda<Func<ParentDto, bool>>(
    Expression.MakeBinary(
        ExpressionType.Equal,
        Expression.Property(Expression.Property(p2, "Child"), "EnumProp"),
        Expression.Constant(DayOfWeek.Monday)
    ),
    p2
);

// ($i.Child).EnumProp == .Constant<System.DayOfWeek>(Monday)
```

I think, we could put our expression builder in line with what C# compiler generates. However, as you mentioned, the query fails with and without typecast. I prefer not to take any action at this time.
