### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by KaungZawHtet** [DevExpress/DevExtreme.AspNet.Data#495]
In your website, you announce the commercial license and in nuget and this repository, you announce MIT license. What does this mean ? I am a little confuse in your two licensing announcements.

**Comment by AlekseyMartynov** [comment]
Hello,

Would you please specify the URLs and exact product names that you are comparing?

I confirm that 'DevExtreme.AspNet.Data' also known as 'DevExtreme data layer extension for ASP.NET' and its NuGet / NPM distributions are MIT-licensed:
- https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/LICENSE
- https://www.nuget.org/packages/DevExtreme.AspNet.Data
- https://www.npmjs.com/package/devextreme-aspnet-data
- https://www.npmjs.com/package/devextreme-aspnet-data-nojquery

**Comment by KaungZawHtet** [comment]
https://github.com/DevExpress/DevExtreme **vs** https://github.com/DevExpress/DevExtreme.AspNet.Data

**Comment by AlekseyMartynov** [comment]
Thank you.

**DevExtreme** (https://github.com/DevExpress/DevExtreme) is _not_ MIT licensed. There are two licensing options available: DevExtreme Commerical and DevExtreme Non-Commerical. Learn more at https://js.devexpress.com/Licensing/. Should you have further questions, feel free to contact DevExpress Support at https://devexpress.com/sc.

**DevExtreme.AspNet.Data** (https://github.com/DevExpress/DevExtreme.AspNet.Data) is MIT licensed. It is an extension / plugin for DevExtreme data layer.
