### ISSUE TITLE
How to pass allowdiskuse query parameter for mongodb with the DataLoader?  

### ISSUE THREAD

**Issue by Popeye4242** [DevExpress/DevExtreme.AspNet.Data#496]
Hello, 

I am currently running into a memory exception when using the sort option with the devextreme data loader. Therefore I'd like to pass the allowDiskUse parameter to the aggregation, but I don't know how I am supposed to pass it. The parameter is supposed to be passed on the `collection.Aggregate` parameters.

https://www.mongodb.com/community/forums/t/aggregateoptions-allowdiskuse-not-passed-to-server/102498

```
MongoDB.Driver.MongoCommandException: Command aggregate failed: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in..
```

**Comment by AlekseyMartynov** [comment]
Hello,

I think you can pass this option to the `AsQueryable` method of the MongoDB .NET driver . Please refer to https://stackoverflow.com/a/42134173.

Hope this answers your concern.

**Comment by Popeye4242** [comment]
Hello,

yes, it is indeed possible to pass the `AggregateOptions` to the Method.
