### ISSUE TITLE
DataSourceLoadOptions don't work with .NET 6's minimal API

### ISSUE THREAD

**Issue by markallenramirez** [DevExpress/DevExtreme.AspNet.Data#497]
[DataSourceLoadOptions](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/master/net/Sample/DataSourceLoadOptions.cs) extends _IModelBinder_ for model binding. However, .NET 6's minimal API has no support for model binding (_IModelBinder_) (see [Differences between minimal APIs and APIs with controllers](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio#differences-between-minimal-apis-and-apis-with-controllers)).

The current workaround is to extend the _DataSourceLoadOptions_ class to implement [custom binding](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#custom-binding) manually. For example, using [BindAsync](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#bindasync):
```
public class MyDataSourceLoadOptions : DataSourceLoadOptions
{
    public static ValueTask<MyDataSourceLoadOptions> BindAsync(HttpContext httpContext)
    {
        var loadOptions = new MyDataSourceLoadOptions();
        DataSourceLoadOptionsParser.Parse(loadOptions, key => httpContext.Request.Query[key]);
        return ValueTask.FromResult(loadOptions);
    }
}
```
Usage:
```
app.MapGet("/SampleAPI/Get", (MyDataSourceLoadOptions loadOptions) =>
{
    return DataSourceLoader.Load(SampleData.Orders, loadOptions);
});
```
DataSourceLoadOptions should support minimal API custom binding out of the box.

**Comment by VladNK** [comment]
Hi,

Thank you for reaching out to us.

We currently have no plans to implement this feature.
The workaround you suggested is great, and I believe you can use it as a solution.
