### ISSUE TITLE
AvgAggregator and RemoteAvgAggregator not using IEnumerable Average()

### ISSUE THREAD

**Issue by bigpixventure** [DevExpress/DevExtreme.AspNet.Data#498]
Hi, i'm wondering why none of the both AVG aggregators use the corresponding method IEnumerable Average() which, in case of remote operations enabled, results in an AVG aggregation in Database. Everything would be fine :-)
We have a large amount of data (1.500.000 rows) and if we setup SummaryType.Avg then Linq gererates a DB-statement that fetches all rows. no COUNT(*) or even AVG(...). This results in an extremely hungry query and our Application freezes.
I searched for AVG on your github-repository and figured out, that the specific AVG aggregators use a combination of SUM and COUNT. Why? What was the reason for this solution?
many thanks in advance and best regards
Henry from Germany

**Comment by AlekseyMartynov** [comment]
Hello,

> if we setup SummaryType.Avg then Linq gererates a DB-statement that fetches all rows.

If the LINQ provider is EF Core version below 5, then we indeed don't translate AVG due to a known issue
https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/72b02552f986a13f136d1f537f0bae7200edf886/net/DevExtreme.AspNet.Data/DataSourceLoadContext.cs#L122-L126

> the specific AVG aggregators use a combination of SUM and COUNT. Why? What was the reason for this solution?

This is a design decision that we made initially. Allows us to calculate multilevel groups with their standard summaries in a single LINQ query. We only query for lower level groups, then further aggregation is executed in memory.

**Comment by bigpixventure** [comment]
Hi,
very quick reply 😊. Nice …
 
Okay, i see. That was our assumption too.
But there is one thing we don‘t understand. 
With SQL debugging enabled, we see a „select * from …“ query, although we allways group by „year“ (part of datetime). But there is no „group by“ and no aggregation at all, and that is the time where our system freezes.
If we don’t summarize by „avg“, we get the correct „select sum(…) group by …“ query. 
So far i understand your code, you combine SUM and COUNT aggregation to calculate the AVG. But why does it select all rows, which means 1.500.000 in our case, if we use „avg“ in a very standard summary. I would expect an SUM(…) and COUNT(…) query.   

DataLoadOptions:
{
  "Group": [
    {
      "IsExpanded": false,
      "Selector": "BetreuendeFiliale"
    },
    {
      "GroupInterval": "year",
      "IsExpanded": false,
      "Selector": "Belegdatum"
    }
  ],
  "GroupSummary": [
    {
      "Selector": "VKBrutto",
      "SummaryType": "sum"
    },
    {
      "Selector": "Marge",
      "SummaryType": "avg"
    }
  ]
}

Thanks again and best regards
Henry

Von: AlekseyMartynov
Gesendet: Montag, 31. Januar 2022 16:55
An: DevExpress/DevExtreme.AspNet.Data
Cc: Henry Eberhardt; Author
Betreff: Re: [DevExpress/DevExtreme.AspNet.Data] AvgAggregator andRemoteAvgAggregator not using IEnumerable Average() (Issue #498)

Hello,
if we setup SummaryType.Avg then Linq gererates a DB-statement that fetches all rows.
If the LINQ provider is EF Core version below 5, then we indeed don't translate AVG due to a known issue
https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/72b02552f986a13f136d1f537f0bae7200edf886/net/DevExtreme.AspNet.Data/DataSourceLoadContext.cs#L122-L126
the specific AVG aggregators use a combination of SUM and COUNT. Why? What was the reason for this solution?
This is a design decision that we made initially. Allows us to calculate multilevel groups with their standard summaries in a single LINQ query. We only query for lower level groups, then further aggregation is executed in memory.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bigpixventure** [comment]
Hi,
actually that’s not necessary anymore.
We have more applications running. One of them runs in .NET and uses EntityFramework 6. So we add some routes to get our results from there. 
I have tested ist and it works fine so far. The Aggreator does not use AVG in database, but at least the SUM / COUNT combination. No SELECT * FROM to identify 😊
The next step is to increase all versions in our other applications to get the current EntityFramework working.
Many many thanks
Henry

Von: AlekseyMartynov
Gesendet: Dienstag, 1. Februar 2022 10:06
An: DevExpress/DevExtreme.AspNet.Data
Cc: Henry Eberhardt; Author
Betreff: Re: [DevExpress/DevExtreme.AspNet.Data] AvgAggregator andRemoteAvgAggregator not using IEnumerable Average() (Issue #498)

But why does it select all rows, which means 1.500.000 in our case, if we use „avg“ in a very standard summary. I would expect an SUM(…) and COUNT(…) query.
To accurately answer this question I need to debug a specific case. SQL translation depends on a number of factors, such as the underlying query provider, property data types, our compatibility flags. Would you please isolate the issue into a standalone runnable .NET project and share it with me? No data is required, just .NET code.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
