### ISSUE TITLE
An exception is thrown when Enum values are compared

### ISSUE THREAD

**Issue by ilyapavlovdx** [DevExpress/DevExtreme.AspNet.Data#499]
An exception with the following message is thrown when Enum values are compared by "<" or ">":
>System.InvalidOperationException: The LINQ expression 'DbSet<Note>()
.Where(n => n.Status.CompareTo((object)Read) < 0)' could not be translated.

The issue is reproduced in EF Core v5.06

Filter:

```json
[[["status","<",1],"or",["status","=",null]],"or",[["status","=",1],"and",[[["id","<",99],"or",["id","=",null]],"or",[["id","=",99],"and",["id","<",99]]]]]
```

Data model:

```cs
public class Note
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Status Status { get; set; }
    }
    public enum Status
    {
        Unread = 0,
        Read = 1,
    }
```

**Comment by AlekseyMartynov** [comment]
Thanks @ilyapavlovdx 

Possibly related: https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/493#issuecomment-975428724
