### ISSUE TITLE
Building the /net/Samples/Sample.csproj fails because of missing 'node_modules' directory.

### ISSUE THREAD

**Issue by GPN-Integrationsfonds** [DevExpress/DevExtreme.AspNet.Data#511]
Dear Ladies and Gentlemen,

unfortunately I'm not able to build the Samples solution because the directory 'node_modules' which
is referenced in the 'libman.json' file is missing.

{
  "version": "1.0",
  "libraries": [
    {
      "library": "node_modules/jquery/dist/jquery.js",
      "provider": "filesystem",
      "destination": "wwwroot/lib/"
    },
    
It leads to the following errors during build in VisuasStudio:

![image](https://user-images.githubusercontent.com/100200854/195300672-85c9632b-e7f6-4780-9bad-7d062279306a.png)

Please resolve that issue or add some instructions to the 'README' which tell how to build the project.

Kind regards, G. Poehlmann.

**Comment by AlekseyMartynov** [comment]
Hello,

In Visual Studio, select package.json, then execute the 'Restore Packages' context command:

![img1](https://user-images.githubusercontent.com/4426185/197129506-02e386ae-10b4-45c5-9db3-c294945ff793.png)

Watch the progress in the 'Output / npm' pane:

![img2](https://user-images.githubusercontent.com/4426185/197129632-da546b33-073f-48f8-ae16-f9e4fb51ae0b.png)


### See Also
- https://learn.microsoft.com/en-us/visualstudio/javascript/npm-package-management
