### ISSUE TITLE
Nested Datagrid Excel Export

### ISSUE THREAD

**Issue by Sbhysl** [DevExpress/DevExtreme.AspNet.Data#585]
I create nested datagrid in the link I posted below.
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MasterDetailView/NetCore/Light/ 

I use this DataGridBuilder  **.OnExporting("exporting")** also I defined js function in cshtml page.

 ### function exporting(e) {
            var workbook = new ExcelJS.Workbook();
            var worksheet = workbook.addWorksheet('Uye_Isyeri_Listesi');

            DevExpress.excelExporter.exportDataGrid({
                component: e.component,
                worksheet: worksheet,
                autoFilterEnabled: true,

            }).then(function () {
                workbook.xlsx.writeBuffer().then(function (buffer) {
                    saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Uye_Isyeri_Listesi.xlsx');
                });
            });
            e.cancel = true;
        }
I tried to export that excel with this export button that devextreme has.

![image](https://user-images.githubusercontent.com/79367225/222522038-1588dacb-ea3b-47da-b218-4b3b970d6635.png)
But all I got main lines(yellow ones). I need to export other datagrid too.(Red part)
![image](https://user-images.githubusercontent.com/79367225/222522724-59cdc341-9f1b-4d86-9c47-091b550ef713.png)

What am I missing?

**Comment by aecceyhan** [comment]
@AlekseyMartynov may I kindly ask for help with this use case?

**Comment by Bykiev** [comment]
Hi, check this ticket: https://supportcenter.devexpress.com/ticket/details/t999172/datagrid-master-detail-grid-export-to-excel-functionality
