### ISSUE TITLE
Migrate the DevExtreme data library Sample project to ASP.NET Core 1.0.0

### ISSUE THREAD

**Issue by San4es** [DevExpress/DevExtreme.AspNet.Data#66]
Now the DevExtreme.AspNet.Data library has several incompatibility issues with the ASP.NET Core 1.0.0 release version.

For instance, the Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult.Success method signature was changed in 
[this commit](https://github.com/aspnet/Mvc/commit/88c9ae6588dd36b7a65d5066c0507dc3cec595a5#diff-2cbda9ff7d5a156fc478b38a437e518bL36) and the [DevExtreme.AspNet.Data.DataSourceLoadOptionsBinder.BindModelAsync](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/dd7e2941934f55aa14017ff3774f85adb145df88/net/Sample/DataSourceLoadOptions.cs#L20) method raises the System.MissingMethodException error.

**Comment by AlekseyMartynov** [comment]
Hi @San4es 
The library itself doesn't depend on AspNet.
I guess you are talking about the Sample project, aren't you?

**Comment by San4es** [comment]
Hi @AlekseyMartynov,

Yes.
