### ISSUE TITLE
support $select functionality

### ISSUE THREAD

**Issue by drezni01** [DevExpress/DevExtreme.AspNet.Data#75]
Currently the DataSourceLoader does not support the $select functionality.  At the minimum, can you please make the following class public so that I can replicate that functionality on my side by using this class?
DevExtreme.AspNet.Data.DataSourceLoadResult

You can see how I'm using that here:  https://www.devexpress.com/Support/Center/Question/Details/T430399

**Comment by AlekseyMartynov** [comment]
We've just published version `1.3.0-rc1`:

* https://www.nuget.org/packages/DevExtreme.AspNet.Data/1.3.0-rc1
* `npm i devextreme-aspnet-data@1.3.0-rc1`

The `DataSourceLoadOptionsBase.Select` member has been added.

Also, `DataSourceLoadResult` has been renamed and made public in the context of #127
