### ISSUE TITLE
Questions on dx.aspnet.data.js

### ISSUE THREAD

**Issue by sanket360** [DevExpress/DevExtreme.AspNet.Data#79]
1. Does this dx.aspnet.data.js available on npm? similar to devextreme-angular2.

2. Is there a way to pass parameter in GET url? Any documentation available for this?
`pivotStore = DevExpress.data.AspNet.createStore({ "loadUrl": "/Detail/Get", });`

**Comment by AlekseyMartynov** [comment]
1. There's no npm for the script as of today.  It's available only via [bower](https://bower.io/) as "devextreme-aspnet-data".
2. Query string parameters can be passed in `loadParams`. Check how the detail grid is defined in the Sample app ([Index.cshtml](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/1.0.0/net/Sample/Views/Home/Index.cshtml#L90-L93))

**Comment by sanket360** [comment]
Thanks @AlekseyMartynov for quick response :+1:

**Comment by AlekseyMartynov** [comment]
@sanket360 
Good news.
The script is in NPM: https://www.npmjs.com/package/devextreme-aspnet-data
