### ISSUE TITLE
Interval grouping by Nullable<DateTime> doesn't work properly

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/DevExtreme.AspNet.Data#85]
See the [Filter row does not filter properly for nullable date field](https://www.devexpress.com/Support/Center/Question/Details/T458279) ticket for details.
[T458279.zip](https://github.com/DevExpress/DevExtreme.AspNet.Data/files/630743/T458279.zip)

**Comment by AlekseyMartynov** [comment]
Test case (in the context of `GroupHelperTests`):

```c#
var data = new[] {
    new { d = new DateTime?(new DateTime(1996, 7, 4)) },
    new { d = new DateTime?() }
};

var groups = CreateHelper(data).Group(data, new[] {
    new GroupingInfo { Selector = "d", GroupInterval = "year", IsExpanded = false },
    new GroupingInfo { Selector = "d", GroupInterval = "month", IsExpanded = false },
    new GroupingInfo { Selector = "d", GroupInterval = "day", IsExpanded = false }
});
```

@vconst @Alyar666 
What behavior we expect?
Should `null` values be ignored during the calculation of date group intervals?

**Comment by vconst** [comment]
The null values should not be ignored. The groups array should contains item with key value null. The grid ignores the items property in header filter when key is null.

**Comment by AlekseyMartynov** [comment]
Do I understand correctly: there must be 3 group levels with `null` keys?

**Comment by vconst** [comment]
Yes

**Comment by AlekseyMartynov** [comment]
Fix will be included in release 1.2.1

**Comment by GiviKDev** [comment]
Hello,

Header Filter not working with `Nullable<DateTime>` when `RemoteOperations` is set to `true`.

`public static object Load<T>(IQueryable<T> source, DataSourceLoadOptionsBase options);`
 method throws an exception:

```
Value cannot be null.
Parameter name: constructor
```

Version 1.2.3

**Comment by AlekseyMartynov** [comment]
@roman-simionov PTAL

**Comment by roman-simionov** [comment]
Hello @GiviKDev,

My attempts to reproduce the issue with the [sample project](https://github.com/DevExpress/DevExtreme.AspNet.Data/files/749878/T458279.zip) were unsuccessful. The header filter works correctly with `Nullable<DateTime>` and the enabled `RemoteOperations` options. Would you please update my sample to illustrate the issue.

**Comment by GiviKDev** [comment]
Hello, I updated your sample project, where you can reproduce current bug.

[T458279.zip](https://github.com/DevExpress/DevExtreme.AspNet.Data/files/750991/T458279.zip)

**Comment by roman-simionov** [comment]
@GikiDev, thank you for your reply. Now I see the issue appears when EF is used. We will fix it in the context of [this issue](https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/100)

**Comment by AlekseyMartynov** [comment]
Hi @GiviKDev 

Would you please check the fixed NuGet from https://ci.appveyor.com/project/dxrobot/devextreme-aspnet-data/build/244/artifacts ?

You will need the following binding redirect in web.config:

```xml
<dependentAssembly>
 <assemblyIdentity name="DevExtreme.AspNet.Data" publicKeyToken="982f5dab1439d0f7"/>
 <bindingRedirect oldVersion="0.0.0.0-99.0.0.0" newVersion="99.0.0.0"/>
</dependentAssembly>
```

P.S. [How to install a Nuget Package .nupkg file locally](http://stackoverflow.com/questions/10240029)

**Comment by GiviKDev** [comment]
Hello,

Thanks, it's working like a charm.
