### ISSUE TITLE
The "sum" summary is not calculated for the TimeSpan column

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/DevExtreme.AspNet.Data#86]
See the [DataGrid MVC Wrapper - Summary for TimeSpan values is not calculated](https://www.devexpress.com/Support/Center/Question/Details/T458296) ticket for details.
[T458296.zip](https://github.com/DevExpress/DevExtreme.AspNet.Data/files/633565/T458296.zip)

**Comment by AlekseyMartynov** [comment]
Reproduced.

Caused by the fact that we [try to convert to `decimal`](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/1.2.0/net/DevExtreme.AspNet.Data/Aggregation/SumAggregator.cs#L24)

Test case:

```c#
var data = new[] {
    TimeSpan.FromMinutes(1),
    TimeSpan.FromMinutes(2)
};

var totalsInfo = new[] {
    new SummaryInfo { Selector = "this", SummaryType = "sum" }
};

var calculator = new AggregateCalculator<TimeSpan>(data, new DefaultAccessor<TimeSpan>(), totalsInfo, null);
var totals = calculator.Run();

// TODO assert
```

**Comment by AlekseyMartynov** [comment]
We returned this issue back to DevExpress Support Center and processed it there.
https://www.devexpress.com/Support/Center/Question/Details/T458296

P.S. @GoshaFighten 😈
